"""Seed data — auto-generated from intent specification."""

from __future__ import annotations

_SEED: dict[str, list[dict]] = {
    "incident": [
        {"id": "incident-001", "title": "Incident #1", "description": "Sample description for incident record #1", "category": "type-A", "severity": "high", "status": "pending", "latitude": 49.99, "longitude": 49.99, "zone_id": "ZONE-1001", "reporter_name": "incident-reporter_name-1", "reporter_phone": "incident-reporter_phone-1", "affected_population": 10, "estimated_damage": 49.99, "ai_confidence": 49.99, "ai_triage_notes": "incident-ai_triage_notes-1", "photo_url": "https://example.com/incident/1", "audio_transcript": "incident-audio_transcript-1", "assigned_units": ["incident-ref-001"], "resolution_notes": "incident-resolution_notes-1", "response_time_minutes": 49.99, "created_at": "2024-03-11T09:00:00Z"},
        {"id": "incident-002", "title": "Incident #2", "description": "Sample description for incident record #2", "category": "type-B", "severity": "medium", "status": "in_progress", "latitude": 125.5, "longitude": 125.5, "zone_id": "ZONE-1002", "reporter_name": "incident-reporter_name-2", "reporter_phone": "incident-reporter_phone-2", "affected_population": 20, "estimated_damage": 125.5, "ai_confidence": 125.5, "ai_triage_notes": "incident-ai_triage_notes-2", "photo_url": "https://example.com/incident/2", "audio_transcript": "incident-audio_transcript-2", "assigned_units": ["incident-ref-002"], "resolution_notes": "incident-resolution_notes-2", "response_time_minutes": 125.5, "created_at": "2024-03-12T10:00:00Z"},
        {"id": "incident-003", "title": "Incident #3", "description": "Sample description for incident record #3", "category": "type-C", "severity": "low", "status": "completed", "latitude": 29.95, "longitude": 29.95, "zone_id": "ZONE-1003", "reporter_name": "incident-reporter_name-3", "reporter_phone": "incident-reporter_phone-3", "affected_population": 30, "estimated_damage": 29.95, "ai_confidence": 29.95, "ai_triage_notes": "incident-ai_triage_notes-3", "photo_url": "https://example.com/incident/3", "audio_transcript": "incident-audio_transcript-3", "assigned_units": ["incident-ref-003"], "resolution_notes": "incident-resolution_notes-3", "response_time_minutes": 29.95, "created_at": "2024-03-13T11:00:00Z"},
    ],
    "asset": [
        {"id": "asset-001", "name": "Asset #1", "asset_type": "type-A", "status": "pending", "location_address": "asset-location_address-1", "latitude": 49.99, "longitude": 49.99, "zone_id": "ZONE-1001", "install_date": "2024-03-11T07:00:00Z", "expected_lifespan_years": 10, "manufacturer": "asset-manufacturer-1", "model_number": "ASS-0001", "last_inspection_date": "2024-03-11T07:00:00Z", "health_score": 49.99, "replacement_cost": 49.99, "maintenance_budget": 49.99, "sensor_ids": ["asset-ref-001"], "ai_failure_prediction": "asset-ai_failure_prediction-1", "ai_health_trend": "asset-ai_health_trend-1", "created_at": "2024-03-11T09:00:00Z"},
        {"id": "asset-002", "name": "Asset #2", "asset_type": "type-B", "status": "in_progress", "location_address": "asset-location_address-2", "latitude": 125.5, "longitude": 125.5, "zone_id": "ZONE-1002", "install_date": "2024-03-12T08:00:00Z", "expected_lifespan_years": 20, "manufacturer": "asset-manufacturer-2", "model_number": "ASS-0002", "last_inspection_date": "2024-03-12T08:00:00Z", "health_score": 125.5, "replacement_cost": 125.5, "maintenance_budget": 125.5, "sensor_ids": ["asset-ref-002"], "ai_failure_prediction": "asset-ai_failure_prediction-2", "ai_health_trend": "asset-ai_health_trend-2", "created_at": "2024-03-12T10:00:00Z"},
        {"id": "asset-003", "name": "Asset #3", "asset_type": "type-C", "status": "completed", "location_address": "asset-location_address-3", "latitude": 29.95, "longitude": 29.95, "zone_id": "ZONE-1003", "install_date": "2024-03-13T09:00:00Z", "expected_lifespan_years": 30, "manufacturer": "asset-manufacturer-3", "model_number": "ASS-0003", "last_inspection_date": "2024-03-13T09:00:00Z", "health_score": 29.95, "replacement_cost": 29.95, "maintenance_budget": 29.95, "sensor_ids": ["asset-ref-003"], "ai_failure_prediction": "asset-ai_failure_prediction-3", "ai_health_trend": "asset-ai_health_trend-3", "created_at": "2024-03-13T11:00:00Z"},
    ],
    "sensor": [
        {"id": "sensor-001", "name": "Sensor #1", "sensor_type": "type-A", "status": "pending", "latitude": 49.99, "longitude": 49.99, "zone_id": "ZONE-1001", "asset_id": "ASSET-1001", "vendor": "sensor-vendor-1", "protocol": "sensor-protocol-1", "last_reading_value": 49.99, "last_reading_unit": "sensor-last_reading_unit-1", "last_reading_timestamp": "sensor-last_reading_timestamp-1", "threshold_min": 49.99, "threshold_max": 49.99, "alert_enabled": True, "battery_level": 49.99, "firmware_version": "sensor-firmware_version-1", "calibration_date": "2024-03-11T07:00:00Z", "created_at": "2024-03-11T09:00:00Z"},
        {"id": "sensor-002", "name": "Sensor #2", "sensor_type": "type-B", "status": "in_progress", "latitude": 125.5, "longitude": 125.5, "zone_id": "ZONE-1002", "asset_id": "ASSET-1002", "vendor": "sensor-vendor-2", "protocol": "sensor-protocol-2", "last_reading_value": 125.5, "last_reading_unit": "sensor-last_reading_unit-2", "last_reading_timestamp": "sensor-last_reading_timestamp-2", "threshold_min": 125.5, "threshold_max": 125.5, "alert_enabled": False, "battery_level": 125.5, "firmware_version": "sensor-firmware_version-2", "calibration_date": "2024-03-12T08:00:00Z", "created_at": "2024-03-12T10:00:00Z"},
        {"id": "sensor-003", "name": "Sensor #3", "sensor_type": "type-C", "status": "completed", "latitude": 29.95, "longitude": 29.95, "zone_id": "ZONE-1003", "asset_id": "ASSET-1003", "vendor": "sensor-vendor-3", "protocol": "sensor-protocol-3", "last_reading_value": 29.95, "last_reading_unit": "sensor-last_reading_unit-3", "last_reading_timestamp": "sensor-last_reading_timestamp-3", "threshold_min": 29.95, "threshold_max": 29.95, "alert_enabled": True, "battery_level": 29.95, "firmware_version": "sensor-firmware_version-3", "calibration_date": "2024-03-13T09:00:00Z", "created_at": "2024-03-13T11:00:00Z"},
    ],
    "service_request": [
        {"id": "service_request-001", "title": "ServiceRequest #1", "description": "Sample description for servicerequest record #1", "category": "type-A", "priority": "high", "status": "pending", "citizen_name": "servicerequest-citizen_name-1", "citizen_email": "servicerequest-citizen_email-1", "citizen_phone": "servicerequest-citizen_phone-1", "latitude": 49.99, "longitude": 49.99, "zone_id": "ZONE-1001", "assigned_team": "servicerequest-assigned_team-1", "estimated_completion_date": "2024-03-11T07:00:00Z", "ai_duplicate_score": 49.99, "ai_category_confidence": 49.99, "ai_suggested_resolution": "servicerequest-ai_suggested_resolution-1", "photo_url": "https://example.com/servicerequest/1", "satisfaction_rating": 10, "created_at": "2024-03-11T09:00:00Z"},
        {"id": "service_request-002", "title": "ServiceRequest #2", "description": "Sample description for servicerequest record #2", "category": "type-B", "priority": "medium", "status": "in_progress", "citizen_name": "servicerequest-citizen_name-2", "citizen_email": "servicerequest-citizen_email-2", "citizen_phone": "servicerequest-citizen_phone-2", "latitude": 125.5, "longitude": 125.5, "zone_id": "ZONE-1002", "assigned_team": "servicerequest-assigned_team-2", "estimated_completion_date": "2024-03-12T08:00:00Z", "ai_duplicate_score": 125.5, "ai_category_confidence": 125.5, "ai_suggested_resolution": "servicerequest-ai_suggested_resolution-2", "photo_url": "https://example.com/servicerequest/2", "satisfaction_rating": 20, "created_at": "2024-03-12T10:00:00Z"},
        {"id": "service_request-003", "title": "ServiceRequest #3", "description": "Sample description for servicerequest record #3", "category": "type-C", "priority": "low", "status": "completed", "citizen_name": "servicerequest-citizen_name-3", "citizen_email": "servicerequest-citizen_email-3", "citizen_phone": "servicerequest-citizen_phone-3", "latitude": 29.95, "longitude": 29.95, "zone_id": "ZONE-1003", "assigned_team": "servicerequest-assigned_team-3", "estimated_completion_date": "2024-03-13T09:00:00Z", "ai_duplicate_score": 29.95, "ai_category_confidence": 29.95, "ai_suggested_resolution": "servicerequest-ai_suggested_resolution-3", "photo_url": "https://example.com/servicerequest/3", "satisfaction_rating": 30, "created_at": "2024-03-13T11:00:00Z"},
    ],
    "transit_route": [
        {"id": "transit_route-001", "name": "TransitRoute #1", "route_number": "TRA-0001", "route_type": "type-A", "status": "pending", "start_location": "transitroute-start_location-1", "end_location": "transitroute-end_location-1", "total_stops": 10, "daily_ridership": 10, "average_delay_minutes": 49.99, "on_time_percentage": 49.99, "fare_revenue_daily": 49.99, "operating_cost_daily": 49.99, "vehicle_count": 10, "zone_ids": ["transitroute-ref-001"], "ai_demand_forecast": "transitroute-ai_demand_forecast-1", "ai_optimization_notes": "transitroute-ai_optimization_notes-1", "last_disruption_reason": "transitroute-last_disruption_reason-1", "created_at": "2024-03-11T09:00:00Z"},
        {"id": "transit_route-002", "name": "TransitRoute #2", "route_number": "TRA-0002", "route_type": "type-B", "status": "in_progress", "start_location": "transitroute-start_location-2", "end_location": "transitroute-end_location-2", "total_stops": 20, "daily_ridership": 20, "average_delay_minutes": 125.5, "on_time_percentage": 125.5, "fare_revenue_daily": 125.5, "operating_cost_daily": 125.5, "vehicle_count": 20, "zone_ids": ["transitroute-ref-002"], "ai_demand_forecast": "transitroute-ai_demand_forecast-2", "ai_optimization_notes": "transitroute-ai_optimization_notes-2", "last_disruption_reason": "transitroute-last_disruption_reason-2", "created_at": "2024-03-12T10:00:00Z"},
        {"id": "transit_route-003", "name": "TransitRoute #3", "route_number": "TRA-0003", "route_type": "type-C", "status": "completed", "start_location": "transitroute-start_location-3", "end_location": "transitroute-end_location-3", "total_stops": 30, "daily_ridership": 30, "average_delay_minutes": 29.95, "on_time_percentage": 29.95, "fare_revenue_daily": 29.95, "operating_cost_daily": 29.95, "vehicle_count": 30, "zone_ids": ["transitroute-ref-003"], "ai_demand_forecast": "transitroute-ai_demand_forecast-3", "ai_optimization_notes": "transitroute-ai_optimization_notes-3", "last_disruption_reason": "transitroute-last_disruption_reason-3", "created_at": "2024-03-13T11:00:00Z"},
    ],
    "vehicle": [
        {"id": "vehicle-001", "name": "Vehicle #1", "vehicle_type": "type-A", "status": "pending", "license_plate": "vehicle-license_plate-1", "vin_number": "VEH-0001", "current_latitude": 49.99, "current_longitude": 49.99, "assigned_department": "vehicle-assigned_department-1", "driver_name": "vehicle-driver_name-1", "fuel_level_pct": 49.99, "odometer_miles": 10, "last_maintenance_date": "2024-03-11T07:00:00Z", "next_maintenance_due": "vehicle-next_maintenance_due-1", "maintenance_cost_ytd": 49.99, "ai_maintenance_prediction": "vehicle-ai_maintenance_prediction-1", "gps_speed_mph": 49.99, "engine_health_score": 49.99, "created_at": "2024-03-11T09:00:00Z"},
        {"id": "vehicle-002", "name": "Vehicle #2", "vehicle_type": "type-B", "status": "in_progress", "license_plate": "vehicle-license_plate-2", "vin_number": "VEH-0002", "current_latitude": 125.5, "current_longitude": 125.5, "assigned_department": "vehicle-assigned_department-2", "driver_name": "vehicle-driver_name-2", "fuel_level_pct": 125.5, "odometer_miles": 20, "last_maintenance_date": "2024-03-12T08:00:00Z", "next_maintenance_due": "vehicle-next_maintenance_due-2", "maintenance_cost_ytd": 125.5, "ai_maintenance_prediction": "vehicle-ai_maintenance_prediction-2", "gps_speed_mph": 125.5, "engine_health_score": 125.5, "created_at": "2024-03-12T10:00:00Z"},
        {"id": "vehicle-003", "name": "Vehicle #3", "vehicle_type": "type-C", "status": "completed", "license_plate": "vehicle-license_plate-3", "vin_number": "VEH-0003", "current_latitude": 29.95, "current_longitude": 29.95, "assigned_department": "vehicle-assigned_department-3", "driver_name": "vehicle-driver_name-3", "fuel_level_pct": 29.95, "odometer_miles": 30, "last_maintenance_date": "2024-03-13T09:00:00Z", "next_maintenance_due": "vehicle-next_maintenance_due-3", "maintenance_cost_ytd": 29.95, "ai_maintenance_prediction": "vehicle-ai_maintenance_prediction-3", "gps_speed_mph": 29.95, "engine_health_score": 29.95, "created_at": "2024-03-13T11:00:00Z"},
    ],
    "zone": [
        {"id": "zone-001", "name": "Zone #1", "zone_code": "zone-zone_code-1", "zone_type": "type-A", "status": "pending", "population": 10, "area_sq_miles": 49.99, "council_district": 10, "emergency_contacts": ["zone-ref-001"], "active_incident_count": 10, "active_sensor_count": 10, "active_asset_count": 10, "air_quality_index": 49.99, "noise_level_db": 49.99, "power_load_pct": 49.99, "ai_risk_score": 49.99, "ai_trend_summary": "zone-ai_trend_summary-1", "created_at": "2024-03-11T09:00:00Z"},
        {"id": "zone-002", "name": "Zone #2", "zone_code": "zone-zone_code-2", "zone_type": "type-B", "status": "in_progress", "population": 20, "area_sq_miles": 125.5, "council_district": 20, "emergency_contacts": ["zone-ref-002"], "active_incident_count": 20, "active_sensor_count": 20, "active_asset_count": 20, "air_quality_index": 125.5, "noise_level_db": 125.5, "power_load_pct": 125.5, "ai_risk_score": 125.5, "ai_trend_summary": "zone-ai_trend_summary-2", "created_at": "2024-03-12T10:00:00Z"},
        {"id": "zone-003", "name": "Zone #3", "zone_code": "zone-zone_code-3", "zone_type": "type-C", "status": "completed", "population": 30, "area_sq_miles": 29.95, "council_district": 30, "emergency_contacts": ["zone-ref-003"], "active_incident_count": 30, "active_sensor_count": 30, "active_asset_count": 30, "air_quality_index": 29.95, "noise_level_db": 29.95, "power_load_pct": 29.95, "ai_risk_score": 29.95, "ai_trend_summary": "zone-ai_trend_summary-3", "created_at": "2024-03-13T11:00:00Z"},
    ],
    "work_order": [
        {"id": "work_order-001", "title": "WorkOrder #1", "description": "Sample description for workorder record #1", "work_type": "type-A", "priority": "high", "status": "pending", "asset_id": "ASSET-1001", "assigned_team": "workorder-assigned_team-1", "scheduled_date": "2024-03-11T07:00:00Z", "estimated_hours": 49.99, "actual_hours": 49.99, "parts_cost": 49.99, "labor_cost": 49.99, "total_cost": 49.99, "ai_generated": True, "ai_justification": "workorder-ai_justification-1", "completion_notes": "workorder-completion_notes-1", "quality_rating": 10, "created_at": "2024-03-11T09:00:00Z"},
        {"id": "work_order-002", "title": "WorkOrder #2", "description": "Sample description for workorder record #2", "work_type": "type-B", "priority": "medium", "status": "in_progress", "asset_id": "ASSET-1002", "assigned_team": "workorder-assigned_team-2", "scheduled_date": "2024-03-12T08:00:00Z", "estimated_hours": 125.5, "actual_hours": 125.5, "parts_cost": 125.5, "labor_cost": 125.5, "total_cost": 125.5, "ai_generated": False, "ai_justification": "workorder-ai_justification-2", "completion_notes": "workorder-completion_notes-2", "quality_rating": 20, "created_at": "2024-03-12T10:00:00Z"},
        {"id": "work_order-003", "title": "WorkOrder #3", "description": "Sample description for workorder record #3", "work_type": "type-C", "priority": "low", "status": "completed", "asset_id": "ASSET-1003", "assigned_team": "workorder-assigned_team-3", "scheduled_date": "2024-03-13T09:00:00Z", "estimated_hours": 29.95, "actual_hours": 29.95, "parts_cost": 29.95, "labor_cost": 29.95, "total_cost": 29.95, "ai_generated": True, "ai_justification": "workorder-ai_justification-3", "completion_notes": "workorder-completion_notes-3", "quality_rating": 30, "created_at": "2024-03-13T11:00:00Z"},
    ],
    "audit_log": [
        {"id": "audit_log-001", "event_type": "type-A", "agent_name": "auditlog-agent_name-1", "user_id": "USER-1001", "user_role": "auditlog-user_role-1", "prompt_text": "auditlog-prompt_text-1", "completion_text": "auditlog-completion_text-1", "token_count_prompt": 10, "token_count_completion": 10, "latency_ms": 10, "model_name": "auditlog-model_name-1", "content_safety_result": "auditlog-content_safety_result-1", "content_safety_categories": "auditlog-content_safety_categories-1", "pii_detected": True, "session_id": "SESSION-1001", "correlation_id": "CORRELATION-1001", "ip_address": "192.168.1.11", "status": "pending", "created_at": "2024-03-11T09:00:00Z"},
        {"id": "audit_log-002", "event_type": "type-B", "agent_name": "auditlog-agent_name-2", "user_id": "USER-1002", "user_role": "auditlog-user_role-2", "prompt_text": "auditlog-prompt_text-2", "completion_text": "auditlog-completion_text-2", "token_count_prompt": 20, "token_count_completion": 20, "latency_ms": 20, "model_name": "auditlog-model_name-2", "content_safety_result": "auditlog-content_safety_result-2", "content_safety_categories": "auditlog-content_safety_categories-2", "pii_detected": False, "session_id": "SESSION-1002", "correlation_id": "CORRELATION-1002", "ip_address": "192.168.1.12", "status": "in_progress", "created_at": "2024-03-12T10:00:00Z"},
        {"id": "audit_log-003", "event_type": "type-C", "agent_name": "auditlog-agent_name-3", "user_id": "USER-1003", "user_role": "auditlog-user_role-3", "prompt_text": "auditlog-prompt_text-3", "completion_text": "auditlog-completion_text-3", "token_count_prompt": 30, "token_count_completion": 30, "latency_ms": 30, "model_name": "auditlog-model_name-3", "content_safety_result": "auditlog-content_safety_result-3", "content_safety_categories": "auditlog-content_safety_categories-3", "pii_detected": True, "session_id": "SESSION-1003", "correlation_id": "CORRELATION-1003", "ip_address": "192.168.1.13", "status": "completed", "created_at": "2024-03-13T11:00:00Z"},
    ],
}


def get_seed_data(entity_name: str) -> list[dict]:
    """Return seed records for the given entity type."""
    return _SEED.get(entity_name, [])
