"""Tests for Pipeline Tiers -- generator filtering by complexity level (consolidated)."""

import pytest
from src.orchestrator.generators.protocol import (
    GeneratorAdapter,
    GeneratorContext,
    GeneratorRegistry,
    _bridge_spec_only,
    create_default_registry,
)
from src.orchestrator.intent_schema import IntentSpec, PipelineTier, PlanOutput


def _make_spec(tier: PipelineTier = PipelineTier.STANDARD) -> IntentSpec:
    return IntentSpec(
        project_name="test-tiers",
        description="Test pipeline tiers",
        raw_intent="test",
        pipeline_tier=tier,
    )


class FakeGenerator:
    """Minimal generator that tracks if it was called."""

    def __init__(self, name: str):
        self.name = name
        self.called = False

    def generate(self, spec):
        self.called = True
        return {f"test/{self.name}.txt": f"generated by {self.name}"}


class TestPipelineTier:
    def test_tier_enum_values(self):
        assert PipelineTier.MICRO.value == "micro"
        assert PipelineTier.STANDARD.value == "standard"
        assert PipelineTier.ENTERPRISE.value == "enterprise"

    def test_default_tier_is_standard(self):
        spec = IntentSpec(
            project_name="test-default",
            description="Test",
            raw_intent="test",
        )
        assert spec.pipeline_tier == PipelineTier.STANDARD


class TestRegistryTierFiltering:
    @pytest.mark.parametrize("tier,expected_called,expected_not_called", [
        (PipelineTier.MICRO, ["micro"], ["standard", "enterprise"]),
        (PipelineTier.STANDARD, ["micro", "standard"], ["enterprise"]),
        (PipelineTier.ENTERPRISE, ["micro", "standard", "enterprise"], []),
    ])
    def test_tier_filtering(self, tier, expected_called, expected_not_called):
        registry = GeneratorRegistry()
        gens = {
            "micro": FakeGenerator("micro"),
            "standard": FakeGenerator("standard"),
            "enterprise": FakeGenerator("enterprise"),
        }

        registry.register("micro", GeneratorAdapter(gens["micro"], _bridge_spec_only), priority=10, min_tier=PipelineTier.MICRO)
        registry.register("standard", GeneratorAdapter(gens["standard"], _bridge_spec_only), priority=20, min_tier=PipelineTier.STANDARD)
        registry.register("enterprise", GeneratorAdapter(gens["enterprise"], _bridge_spec_only), priority=30, min_tier=PipelineTier.ENTERPRISE)

        spec = _make_spec(tier)
        ctx = GeneratorContext()
        registry.run_all(spec, ctx)

        for name in expected_called:
            assert gens[name].called, f"{name} should run at {tier}"
        for name in expected_not_called:
            assert not gens[name].called, f"{name} should NOT run at {tier}"


class TestDefaultRegistryTiers:
    def test_default_registry_has_tier_assignments(self):
        registry = create_default_registry()
        # Core generators should be MICRO tier (always run)
        for name in ("bicep", "cicd", "app", "tests"):
            assert name in registry

        # Enterprise-only generators
        for name in ("alerts", "dashboard", "cost"):
            assert name in registry

    def test_default_registry_micro_tier_subset(self):
        """MICRO tier should produce significantly fewer files."""
        registry = create_default_registry()
        spec = _make_spec(PipelineTier.MICRO)
        ctx = GeneratorContext(plan=PlanOutput(
            title="Test",
            summary="Test plan",
            components=[],
            decisions=[],
        ))
        files = registry.run_all(spec, ctx)

        # MICRO should NOT have frontend, docs, alerts, dashboard, cost
        assert not any(k.startswith("frontend/") for k in files), "MICRO should skip frontend"
        assert not any(k.startswith("docs/cost") for k in files), "MICRO should skip cost estimates"
