"""Resource Plugins -- custom Azure resource Bicep modules.

Each plugin generates Bicep modules for Azure resources not included
in the core BicepGenerator (Service Bus, Event Grid, Front Door, etc.).
Plugins use ``applies_to(spec)`` to decide whether to activate.
"""

from __future__ import annotations

from dataclasses import dataclass

from src.orchestrator.intent_schema import IntentSpec
from src.orchestrator.logging import get_logger

logger = get_logger(__name__)


@dataclass(frozen=True)
class ResourcePluginMeta:
    """Metadata describing a resource plugin's capabilities."""

    resource_type: str
    bicep_prefix: str
    description: str
    azure_provider: str


class ServiceBusPlugin:
    """Generates Azure Service Bus Bicep module for event-driven workloads."""

    meta = ResourcePluginMeta(
        resource_type="service-bus",
        bicep_prefix="sb",
        description="Azure Service Bus namespace with queues and topics",
        azure_provider="Microsoft.ServiceBus",
    )

    def applies_to(self, spec: IntentSpec) -> bool:
        keywords = {"event-driven", "message", "queue", "topic", "pub/sub", "service bus", "async", "decouple"}
        raw = spec.raw_intent.lower()
        return any(kw in raw for kw in keywords)

    def generate(self, spec: IntentSpec, **kwargs) -> dict[str, str]:
        name = f"sb-{spec.project_name}-{spec.environment}"
        tags = _common_tags(spec)
        return {
            "infra/bicep/modules/service-bus.bicep": f"""\
// Azure Service Bus Namespace
// Generated by: resource_plugin / ServiceBusPlugin

@description('Service Bus namespace for async messaging')
param location string = resourceGroup().location
param environmentName string = '{spec.environment}'
param workloadName string = '{spec.project_name}'
param managedIdentityPrincipalId string

var sbName = '{name}'

resource serviceBusNamespace 'Microsoft.ServiceBus/namespaces@2022-10-01-preview' = {{
  name: sbName
  location: location
  sku: {{
    name: 'Standard'
    tier: 'Standard'
  }}
  tags: {tags}
  properties: {{
    minimumTlsVersion: '1.2'
    publicNetworkAccess: 'Enabled'
    disableLocalAuth: true
  }}
}}

// Default queue
resource defaultQueue 'Microsoft.ServiceBus/namespaces/queues@2022-10-01-preview' = {{
  parent: serviceBusNamespace
  name: '${{workloadName}}-events'
  properties: {{
    maxDeliveryCount: 10
    lockDuration: 'PT1M'
    defaultMessageTimeToLive: 'P14D'
    deadLetteringOnMessageExpiration: true
  }}
}}

// Default topic
resource defaultTopic 'Microsoft.ServiceBus/namespaces/topics@2022-10-01-preview' = {{
  parent: serviceBusNamespace
  name: '${{workloadName}}-notifications'
  properties: {{
    defaultMessageTimeToLive: 'P14D'
    maxSizeInMegabytes: 1024
  }}
}}

// RBAC: Azure Service Bus Data Sender for managed identity
resource senderRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {{
  name: guid(serviceBusNamespace.id, managedIdentityPrincipalId, '69a216fc-b8fb-44d8-bc22-1f3c2cd27a39')
  scope: serviceBusNamespace
  properties: {{
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '69a216fc-b8fb-44d8-bc22-1f3c2cd27a39')
    principalId: managedIdentityPrincipalId
    principalType: 'ServicePrincipal'
  }}
}}

// RBAC: Azure Service Bus Data Receiver
resource receiverRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {{
  name: guid(serviceBusNamespace.id, managedIdentityPrincipalId, '4f6d3b9b-027b-4f4c-9142-0e5a2a2247e0')
  scope: serviceBusNamespace
  properties: {{
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '4f6d3b9b-027b-4f4c-9142-0e5a2a2247e0')
    principalId: managedIdentityPrincipalId
    principalType: 'ServicePrincipal'
  }}
}}

output serviceBusId string = serviceBusNamespace.id
output serviceBusEndpoint string = serviceBusNamespace.properties.serviceBusEndpoint
""",
        }


class EventGridPlugin:
    """Generates Azure Event Grid Bicep module for event-driven architectures."""

    meta = ResourcePluginMeta(
        resource_type="event-grid",
        bicep_prefix="evgt",
        description="Azure Event Grid system topic with subscriptions",
        azure_provider="Microsoft.EventGrid",
    )

    def applies_to(self, spec: IntentSpec) -> bool:
        keywords = {"event grid", "event-driven", "webhook", "notification", "reactive", "event mesh"}
        raw = spec.raw_intent.lower()
        return any(kw in raw for kw in keywords)

    def generate(self, spec: IntentSpec, **kwargs) -> dict[str, str]:
        name = f"evgt-{spec.project_name}-{spec.environment}"
        tags = _common_tags(spec)
        return {
            "infra/bicep/modules/event-grid.bicep": f"""\
// Azure Event Grid System Topic
// Generated by: resource_plugin / EventGridPlugin

@description('Event Grid system topic for event routing')
param location string = resourceGroup().location
param workloadName string = '{spec.project_name}'
param environmentName string = '{spec.environment}'
param managedIdentityPrincipalId string

var topicName = '{name}'

resource eventGridTopic 'Microsoft.EventGrid/topics@2023-12-15-preview' = {{
  name: topicName
  location: location
  tags: {tags}
  properties: {{
    inputSchema: 'CloudEventSchemaV1_0'
    publicNetworkAccess: 'Enabled'
    minimumTlsVersionAllowed: '1.2'
    disableLocalAuth: true
  }}
  identity: {{
    type: 'SystemAssigned'
  }}
}}

// RBAC: EventGrid Data Sender
resource senderRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {{
  name: guid(eventGridTopic.id, managedIdentityPrincipalId, 'd5a91429-5739-47e2-a06b-3470a27159e7')
  scope: eventGridTopic
  properties: {{
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'd5a91429-5739-47e2-a06b-3470a27159e7')
    principalId: managedIdentityPrincipalId
    principalType: 'ServicePrincipal'
  }}
}}

output topicId string = eventGridTopic.id
output topicEndpoint string = eventGridTopic.properties.endpoint
""",
        }


class FrontDoorPlugin:
    """Generates Azure Front Door Bicep module for global load balancing."""

    meta = ResourcePluginMeta(
        resource_type="front-door",
        bicep_prefix="afd",
        description="Azure Front Door Standard/Premium with WAF policy",
        azure_provider="Microsoft.Cdn",
    )

    def applies_to(self, spec: IntentSpec) -> bool:
        keywords = {"front door", "cdn", "global", "multi-region", "edge", "load balancing"}
        raw = spec.raw_intent.lower()
        return (
            any(kw in raw for kw in keywords)
            or spec.security.enable_waf
        )

    def generate(self, spec: IntentSpec, **kwargs) -> dict[str, str]:
        name = f"afd-{spec.project_name}-{spec.environment}"
        tags = _common_tags(spec)
        return {
            "infra/bicep/modules/front-door.bicep": f"""\
// Azure Front Door Standard with WAF Policy
// Generated by: resource_plugin / FrontDoorPlugin

@description('Front Door profile for global load balancing and WAF')
param location string = 'global'
param workloadName string = '{spec.project_name}'
param environmentName string = '{spec.environment}'
param backendAddress string

var profileName = '{name}'
var wafPolicyName = 'wafpol${{replace(workloadName, '-', '')}}${{environmentName}}'

resource frontDoorProfile 'Microsoft.Cdn/profiles@2023-05-01' = {{
  name: profileName
  location: location
  tags: {tags}
  sku: {{
    name: 'Standard_AzureFrontDoor'
  }}
}}

resource wafPolicy 'Microsoft.Network/FrontDoorWebApplicationFirewallPolicies@2022-05-01' = {{
  name: wafPolicyName
  location: location
  tags: {tags}
  properties: {{
    policySettings: {{
      enabledState: 'Enabled'
      mode: 'Prevention'
      requestBodyCheck: 'Enabled'
    }}
    managedRules: {{
      managedRuleSets: [
        {{
          ruleSetType: 'Microsoft_DefaultRuleSet'
          ruleSetVersion: '2.1'
          ruleSetAction: 'Block'
        }}
        {{
          ruleSetType: 'Microsoft_BotManagerRuleSet'
          ruleSetVersion: '1.0'
          ruleSetAction: 'Block'
        }}
      ]
    }}
  }}
}}

resource endpoint 'Microsoft.Cdn/profiles/afdEndpoints@2023-05-01' = {{
  parent: frontDoorProfile
  name: '${{workloadName}}-endpoint'
  location: location
  properties: {{
    enabledState: 'Enabled'
  }}
}}

resource originGroup 'Microsoft.Cdn/profiles/originGroups@2023-05-01' = {{
  parent: frontDoorProfile
  name: 'default-origin-group'
  properties: {{
    loadBalancingSettings: {{
      sampleSize: 4
      successfulSamplesRequired: 3
      additionalLatencyInMilliseconds: 50
    }}
    healthProbeSettings: {{
      probePath: '/health'
      probeRequestType: 'HEAD'
      probeProtocol: 'Https'
      probeIntervalInSeconds: 30
    }}
  }}
}}

resource origin 'Microsoft.Cdn/profiles/originGroups/origins@2023-05-01' = {{
  parent: originGroup
  name: 'backend-origin'
  properties: {{
    hostName: backendAddress
    httpPort: 80
    httpsPort: 443
    originHostHeader: backendAddress
    priority: 1
    weight: 1000
    enforceCertificateNameCheck: true
  }}
}}

output frontDoorId string = frontDoorProfile.id
output endpointHostName string = endpoint.properties.hostName
""",
        }


def _common_tags(spec: IntentSpec) -> str:
    """Generate Bicep tags object literal."""
    return f"""{{
    project: '{spec.project_name}'
    environment: '{spec.environment}'
    managedBy: 'bicep'
    dataSensitivity: '{spec.security.data_classification}'
  }}"""
