"""Security Plugins -- WAF rules, DDoS controls, and network isolation.

Each plugin generates Bicep modules and/or configuration files for
security infrastructure that extends the base scaffold.
"""

from __future__ import annotations

from src.orchestrator.intent_schema import IntentSpec
from src.orchestrator.logging import get_logger

logger = get_logger(__name__)


class WAFRulesPlugin:
    """Generates Azure Front Door WAF policy with OWASP and bot-protection rules."""

    def applies_to(self, spec: IntentSpec) -> bool:
        return spec.security.enable_waf or "waf" in spec.raw_intent.lower()

    def generate(self, spec: IntentSpec, **kwargs) -> dict[str, str]:
        tags = _common_tags(spec)
        return {
            "infra/bicep/modules/waf-policy.bicep": f"""\
// Azure WAF Policy (Front Door)
// Generated by: security_plugin / WAFRulesPlugin

@description('Web Application Firewall policy')
param location string = 'global'
param workloadName string = '{spec.project_name}'
param environmentName string = '{spec.environment}'

var policyName = 'wafpol${{replace(workloadName, '-', '')}}${{environmentName}}'

resource wafPolicy 'Microsoft.Network/FrontDoorWebApplicationFirewallPolicies@2022-05-01' = {{
  name: policyName
  location: location
  tags: {tags}
  properties: {{
    policySettings: {{
      enabledState: 'Enabled'
      mode: 'Prevention'
      requestBodyCheck: 'Enabled'
      customBlockResponseStatusCode: 403
    }}
    managedRules: {{
      managedRuleSets: [
        {{
          ruleSetType: 'Microsoft_DefaultRuleSet'
          ruleSetVersion: '2.1'
          ruleSetAction: 'Block'
        }}
        {{
          ruleSetType: 'Microsoft_BotManagerRuleSet'
          ruleSetVersion: '1.0'
          ruleSetAction: 'Block'
        }}
      ]
    }}
    customRules: {{
      rules: [
        {{
          name: 'RateLimitRule'
          priority: 1
          enabledState: 'Enabled'
          ruleType: 'RateLimitRule'
          rateLimitDurationInMinutes: 1
          rateLimitThreshold: 100
          action: 'Block'
          matchConditions: [
            {{
              matchVariable: 'RemoteAddr'
              operator: 'IPMatch'
              negateCondition: true
              matchValue: ['0.0.0.0/0']
            }}
          ]
        }}
        {{
          name: 'BlockSQLInjection'
          priority: 2
          enabledState: 'Enabled'
          ruleType: 'MatchRule'
          action: 'Block'
          matchConditions: [
            {{
              matchVariable: 'QueryString'
              operator: 'Contains'
              matchValue: ['SELECT', 'UNION', 'DROP', 'INSERT', '--', ';']
              transforms: ['Uppercase']
            }}
          ]
        }}
      ]
    }}
  }}
}}

output wafPolicyId string = wafPolicy.id
""",
        }


class DDoSProtectionPlugin:
    """Generates Azure DDoS Protection Plan Bicep module."""

    def applies_to(self, spec: IntentSpec) -> bool:
        keywords = {"ddos", "protection", "production", "public"}
        return (
            any(kw in spec.raw_intent.lower() for kw in keywords)
            or spec.environment == "prod"
        )

    def generate(self, spec: IntentSpec, **kwargs) -> dict[str, str]:
        tags = _common_tags(spec)
        return {
            "infra/bicep/modules/ddos-protection.bicep": f"""\
// Azure DDoS Protection Plan
// Generated by: security_plugin / DDoSProtectionPlugin

@description('DDoS Protection Plan for VNet resources')
param location string = resourceGroup().location
param workloadName string = '{spec.project_name}'
param environmentName string = '{spec.environment}'

var planName = 'ddos-${{workloadName}}-${{environmentName}}'

resource ddosPlan 'Microsoft.Network/ddosProtectionPlans@2023-09-01' = {{
  name: planName
  location: location
  tags: {tags}
  properties: {{}}
}}

output ddosPlanId string = ddosPlan.id
""",
        }


class NetworkIsolationPlugin:
    """Generates VNet and NSG Bicep modules for network isolation."""

    def applies_to(self, spec: IntentSpec) -> bool:
        return spec.security.networking.value == "private"

    def generate(self, spec: IntentSpec, **kwargs) -> dict[str, str]:
        tags = _common_tags(spec)
        return {
            "infra/bicep/modules/network-isolation.bicep": f"""\
// Virtual Network + NSG for network isolation
// Generated by: security_plugin / NetworkIsolationPlugin

@description('VNet with subnets and NSG for workload isolation')
param location string = resourceGroup().location
param workloadName string = '{spec.project_name}'
param environmentName string = '{spec.environment}'

var vnetName = 'vnet-${{workloadName}}-${{environmentName}}'
var nsgName = 'nsg-${{workloadName}}-${{environmentName}}'

resource nsg 'Microsoft.Network/networkSecurityGroups@2023-09-01' = {{
  name: nsgName
  location: location
  tags: {tags}
  properties: {{
    securityRules: [
      {{
        name: 'DenyAllInbound'
        properties: {{
          priority: 4096
          direction: 'Inbound'
          access: 'Deny'
          protocol: '*'
          sourceAddressPrefix: '*'
          sourcePortRange: '*'
          destinationAddressPrefix: '*'
          destinationPortRange: '*'
        }}
      }}
      {{
        name: 'AllowHTTPS'
        properties: {{
          priority: 100
          direction: 'Inbound'
          access: 'Allow'
          protocol: 'Tcp'
          sourceAddressPrefix: '*'
          sourcePortRange: '*'
          destinationAddressPrefix: '*'
          destinationPortRange: '443'
        }}
      }}
      {{
        name: 'AllowHealthProbe'
        properties: {{
          priority: 200
          direction: 'Inbound'
          access: 'Allow'
          protocol: 'Tcp'
          sourceAddressPrefix: 'AzureLoadBalancer'
          sourcePortRange: '*'
          destinationAddressPrefix: '*'
          destinationPortRange: '*'
        }}
      }}
    ]
  }}
}}

resource vnet 'Microsoft.Network/virtualNetworks@2023-09-01' = {{
  name: vnetName
  location: location
  tags: {tags}
  properties: {{
    addressSpace: {{
      addressPrefixes: ['10.0.0.0/16']
    }}
    subnets: [
      {{
        name: 'app-subnet'
        properties: {{
          addressPrefix: '10.0.1.0/24'
          networkSecurityGroup: {{
            id: nsg.id
          }}
          delegations: [
            {{
              name: 'containerApps'
              properties: {{
                serviceName: 'Microsoft.App/environments'
              }}
            }}
          ]
        }}
      }}
      {{
        name: 'data-subnet'
        properties: {{
          addressPrefix: '10.0.2.0/24'
          networkSecurityGroup: {{
            id: nsg.id
          }}
          serviceEndpoints: [
            {{ service: 'Microsoft.Storage' }}
            {{ service: 'Microsoft.KeyVault' }}
            {{ service: 'Microsoft.Sql' }}
          ]
        }}
      }}
      {{
        name: 'private-endpoints'
        properties: {{
          addressPrefix: '10.0.3.0/24'
          privateEndpointNetworkPolicies: 'Disabled'
        }}
      }}
    ]
  }}
}}

output vnetId string = vnet.id
output appSubnetId string = vnet.properties.subnets[0].id
output dataSubnetId string = vnet.properties.subnets[1].id
output privateEndpointSubnetId string = vnet.properties.subnets[2].id
""",
        }


def _common_tags(spec: IntentSpec) -> str:
    """Generate Bicep tags object literal."""
    return f"""{{
    project: '{spec.project_name}'
    environment: '{spec.environment}'
    managedBy: 'bicep'
    dataSensitivity: '{spec.security.data_classification}'
  }}"""
