"""Enterprise DevEx Orchestrator -- Generated Application.

Project: smart-city-ai-operations-platform-extre
Description: Build an enterprise-grade AI-powered smart city operations platform that orchestrates **9 distinct domain entities** across every supported data store (Cosmos DB, SQL, Blob Storage, Redis, AI Search, 
Generated by: Enterprise DevEx Orchestrator Agent

This is a production-grade FastAPI application with:
- Health check endpoint
- Managed Identity authentication
- Key Vault integration
- Structured logging
"""

from __future__ import annotations

import logging
import os
from datetime import datetime, timezone

from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient
from fastapi import FastAPI
from fastapi.responses import HTMLResponse, JSONResponse

from azure.storage.blob import BlobServiceClient

from api.v1.router import router as v1_router
from ai.chat import router as ai_router
# -- Configuration ----------------------------------------------------
APP_NAME = "smart-city-ai-operations-platform-extre"
VERSION = "1.0.0"

# -- Logging ----------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format='{"timestamp":"%(asctime)s","level":"%(levelname)s","logger":"%(name)s","message":"%(message)s"}',
)
logger = logging.getLogger(APP_NAME)

# -- FastAPI Application ---------------------------------------------
app = FastAPI(
    title=APP_NAME,
    version=VERSION,
    description="Build an enterprise-grade AI-powered smart city operations platform that orchestrates **9 distinct domain entities** across every supported data store (Cosmos DB, SQL, Blob Storage, Redis, AI Search, ",
    docs_url="/docs",
    redoc_url=None,
)

# -- Mount versioned API router --------------------------------------
app.include_router(v1_router, prefix="/api/v1", tags=["v1"])
app.include_router(ai_router, prefix="/api/v1/ai", tags=["ai"])


# -- Key Vault Client ------------------------------------------------
def get_keyvault_client() -> SecretClient:
    """Create an authenticated Key Vault client using Managed Identity.
    
    Supports two configuration patterns:
    1. KEY_VAULT_URI - full vault URL (https://vault-name.vault.azure.net)
    2. KEY_VAULT_NAME - vault name only (will construct URL)
    """
    credential = DefaultAzureCredential(
        managed_identity_client_id=os.getenv("AZURE_CLIENT_ID")
    )
    
    # Try full URI first (recommended)
    vault_uri = os.getenv("KEY_VAULT_URI", "")
    if vault_uri:
        return SecretClient(vault_url=vault_uri, credential=credential)
    
    # Fallback to name-based construction
    vault_name = os.getenv("KEY_VAULT_NAME", "")
    if not vault_name:
        raise ValueError("Either KEY_VAULT_URI or KEY_VAULT_NAME must be set")
    
    return SecretClient(
        vault_url=f"https://{vault_name}.vault.azure.net",
        credential=credential
    )


# -- Storage Client ---------------------------------------------------
def get_blob_client() -> BlobServiceClient:
    """Create an authenticated Blob Storage client using Managed Identity."""
    credential = DefaultAzureCredential(
        managed_identity_client_id=os.getenv("AZURE_CLIENT_ID")
    )
    account_url = os.getenv("STORAGE_ACCOUNT_URL", "")
    if not account_url:
        raise ValueError("STORAGE_ACCOUNT_URL environment variable not set")
    return BlobServiceClient(account_url=account_url, credential=credential)

# -- Health Endpoint --------------------------------------------------
@app.get("/health")
async def health():
    """Health check endpoint for liveness and readiness probes."""
    return {
        "status": "healthy",
        "service": APP_NAME,
        "version": VERSION,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }


# -- Root Endpoint (Enterprise Dashboard) ------
@app.get("/")
async def root():
    """Root endpoint -- enterprise dashboard."""
    html = f"""<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>{APP_NAME} \u2014 Operations Dashboard</title>
    <style>
        :root {{
            --primary: #0078d4;
            --primary-dark: #005a9e;
            --success: #107c10;
            --warning: #ff8c00;
            --danger: #d13438;
            --bg: #f3f2f1;
            --surface: #ffffff;
            --surface-alt: #faf9f8;
            --text: #323130;
            --text-secondary: #605e5c;
            --border: #edebe9;
            --shadow: 0 2px 8px rgba(0,0,0,.08);
            --shadow-lg: 0 8px 32px rgba(0,0,0,.12);
            --radius: 8px;
            --radius-lg: 12px;
        }}
        * {{ margin:0; padding:0; box-sizing:border-box; }}
        body {{ font-family:'Segoe UI',-apple-system,BlinkMacSystemFont,sans-serif; background:var(--bg); color:var(--text); min-height:100vh; }}
        .topbar {{ background:linear-gradient(135deg,#0078d4 0%,#005a9e 100%); color:white; padding:0 32px; height:48px; display:flex; align-items:center; justify-content:space-between; font-size:13px; box-shadow:0 1px 4px rgba(0,0,0,.15); position:sticky; top:0; z-index:100; }}
        .topbar-brand {{ display:flex; align-items:center; gap:10px; font-weight:600; font-size:14px; }}
        .topbar-brand svg {{ width:20px; height:20px; fill:white; }}
        .topbar-meta {{ display:flex; gap:16px; align-items:center; }}
        .topbar-meta span {{ opacity:.85; }}
        .env-badge {{ background:rgba(255,255,255,.2); padding:2px 10px; border-radius:12px; font-size:11px; text-transform:uppercase; font-weight:600; letter-spacing:.5px; }}
        .status-live {{ display:flex; align-items:center; gap:6px; font-size:12px; }}
        .status-live .dot {{ width:8px; height:8px; border-radius:50%; background:var(--success); animation:pulse 2s infinite; }}
        @keyframes pulse {{ 0%,100%{{opacity:1}} 50%{{opacity:.4}} }}
        .hero {{ background:linear-gradient(180deg,#005a9e 0%,#0078d4 50%,var(--bg) 100%); padding:40px 32px 56px; text-align:center; color:white; }}
        .hero h1 {{ font-size:26px; font-weight:600; margin-bottom:6px; }}
        .hero p {{ font-size:14px; opacity:.9; max-width:600px; margin:0 auto; line-height:1.5; }}
        .hero-pills {{ display:flex; gap:8px; justify-content:center; margin-top:12px; flex-wrap:wrap; }}
        .hero-pills span {{ background:rgba(255,255,255,.15); padding:3px 14px; border-radius:20px; font-size:11px; font-weight:500; }}
        .kpi-bar {{ max-width:1200px; margin:-32px auto 20px; padding:0 24px; display:grid; grid-template-columns:repeat(auto-fit,minmax(180px,1fr)); gap:16px; }}
        .kpi {{ background:var(--surface); border:1px solid var(--border); border-radius:var(--radius-lg); padding:20px; text-align:center; box-shadow:var(--shadow); transition:transform .15s; }}
        .kpi:hover {{ transform:translateY(-2px); box-shadow:var(--shadow-lg); }}
        .kpi .number {{ font-size:32px; font-weight:700; }}
        .kpi .label {{ font-size:11px; text-transform:uppercase; letter-spacing:.8px; color:var(--text-secondary); margin-top:4px; }}
        .kpi.ok .number {{ color:var(--success); }}
        .kpi.warn .number {{ color:var(--warning); }}
        .kpi.danger .number {{ color:var(--danger); }}
        .main {{ max-width:1200px; margin:0 auto 40px; padding:0 24px; }}
        .tab-bar {{ display:flex; gap:0; margin-bottom:0; border-bottom:2px solid var(--border); }}
        .tab {{ padding:12px 24px; font-size:13px; font-weight:600; cursor:pointer; border-bottom:2px solid transparent; margin-bottom:-2px; color:var(--text-secondary); transition:all .15s; }}
        .tab:hover {{ color:var(--text); }}
        .tab.active {{ color:var(--primary); border-bottom-color:var(--primary); }}
        .tab-panel {{ display:none; }}
        .tab-panel.active {{ display:block; }}
        .panel-toolbar {{ display:flex; justify-content:space-between; align-items:center; padding:16px 0; gap:12px; flex-wrap:wrap; }}
        .search-box {{ padding:8px 14px; border:1px solid var(--border); border-radius:var(--radius); font-size:13px; width:280px; outline:none; }}
        .search-box:focus {{ border-color:var(--primary); box-shadow:0 0 0 2px rgba(0,120,212,.15); }}
        .btn {{ padding:8px 18px; border:none; border-radius:var(--radius); font-size:13px; font-weight:600; cursor:pointer; transition:all .15s; display:inline-flex; align-items:center; gap:6px; }}
        .btn-primary {{ background:var(--primary); color:white; }}
        .btn-primary:hover {{ background:var(--primary-dark); }}
        .btn-success {{ background:var(--success); color:white; }}
        .btn-success:hover {{ opacity:.9; }}
        .btn-warning {{ background:var(--warning); color:white; }}
        .btn-warning:hover {{ opacity:.9; }}
        .btn-danger {{ background:var(--danger); color:white; }}
        .btn-danger:hover {{ opacity:.9; }}
        .btn-sm {{ padding:4px 10px; font-size:11px; }}
        .data-table {{ width:100%; border-collapse:separate; border-spacing:0; background:var(--surface); border:1px solid var(--border); border-radius:var(--radius-lg); overflow:hidden; box-shadow:var(--shadow); }}
        .data-table th {{ background:var(--surface-alt); padding:10px 14px; font-size:11px; text-transform:uppercase; letter-spacing:.5px; color:var(--text-secondary); text-align:left; font-weight:600; border-bottom:1px solid var(--border); }}
        .data-table td {{ padding:10px 14px; font-size:13px; border-bottom:1px solid var(--border); }}
        .data-table tr:last-child td {{ border-bottom:none; }}
        .data-table tr:hover td {{ background:#f0f6ff; }}
        .badge {{ display:inline-block; padding:2px 10px; border-radius:12px; font-size:11px; font-weight:600; text-transform:capitalize; }}
        .badge-pending,.badge-draft,.badge-new,.badge-open,.badge-queued,.badge-submitted,.badge-waiting {{ background:#fff3e0; color:#e65100; }}
        .badge-in_progress,.badge-in-progress,.badge-processing,.badge-running,.badge-active,.badge-busy,.badge-executing {{ background:#e3f2fd; color:#1565c0; }}
        .badge-approved,.badge-completed,.badge-processed,.badge-done,.badge-resolved,.badge-closed,.badge-success,.badge-passed,.badge-delivered,.badge-published {{ background:#e6f4ea; color:#1b5e20; }}
        .badge-rejected,.badge-cancelled,.badge-failed,.badge-error,.badge-denied,.badge-expired,.badge-blocked,.badge-terminated {{ background:#fce4ec; color:#b71c1c; }}
        .badge-escalated,.badge-critical,.badge-urgent,.badge-high {{ background:#f3e5f5; color:#6a1b9a; }}
        .badge-on_hold,.badge-on-hold,.badge-paused,.badge-suspended,.badge-deferred,.badge-review,.badge-pending_review {{ background:#e8eaf6; color:#283593; }}
        .badge-inactive,.badge-disabled,.badge-offline,.badge-idle,.badge-standby,.badge-maintenance {{ background:#eceff1; color:#546e7a; }}
        .badge-warning,.badge-degraded,.badge-medium,.badge-partial {{ background:#fffde7; color:#f57f17; }}
        .badge-online,.badge-healthy,.badge-connected,.badge-available,.badge-ready,.badge-low {{ background:#e0f2f1; color:#00695c; }}
        .modal-overlay {{ display:none; position:fixed; top:0; left:0; width:100%; height:100%; background:rgba(0,0,0,.4); z-index:200; justify-content:center; align-items:center; }}
        .modal-overlay.open {{ display:flex; }}
        .modal {{ background:var(--surface); border-radius:var(--radius-lg); box-shadow:var(--shadow-lg); width:480px; max-width:90vw; max-height:80vh; overflow-y:auto; }}
        .modal-header {{ padding:16px 20px; border-bottom:1px solid var(--border); display:flex; justify-content:space-between; align-items:center; }}
        .modal-header h3 {{ font-size:16px; font-weight:600; }}
        .modal-close {{ background:none; border:none; font-size:20px; cursor:pointer; color:var(--text-secondary); }}
        .modal-body {{ padding:20px; }}
        .form-group {{ margin-bottom:14px; }}
        .form-group label {{ display:block; font-size:12px; font-weight:600; color:var(--text-secondary); margin-bottom:4px; text-transform:uppercase; letter-spacing:.3px; }}
        .form-group input,.form-group select,.form-group textarea {{ width:100%; padding:8px 12px; border:1px solid var(--border); border-radius:var(--radius); font-size:13px; outline:none; }}
        .form-group input:focus,.form-group select:focus,.form-group textarea:focus {{ border-color:var(--primary); box-shadow:0 0 0 2px rgba(0,120,212,.15); }}
        .modal-footer {{ padding:12px 20px; border-top:1px solid var(--border); display:flex; justify-content:flex-end; gap:8px; }}
        .toast {{ position:fixed; bottom:24px; right:24px; padding:12px 20px; border-radius:var(--radius); color:white; font-size:13px; font-weight:500; z-index:300; transform:translateY(80px); opacity:0; transition:all .3s; box-shadow:var(--shadow-lg); }}
        .toast.show {{ transform:translateY(0); opacity:1; }}
        .toast.success {{ background:var(--success); }}
        .toast.error {{ background:var(--danger); }}
        .detail-row {{ display:grid; grid-template-columns:140px 1fr; gap:8px; padding:6px 0; border-bottom:1px solid var(--border); font-size:13px; }}
        .detail-row:last-child {{ border-bottom:none; }}
        .detail-row .dl {{ font-weight:600; color:var(--text-secondary); }}
        .empty-state {{ text-align:center; padding:40px; color:var(--text-secondary); }}
        .empty-state .icon {{ font-size:48px; margin-bottom:12px; }}
        .footer {{ text-align:center; padding:24px; font-size:12px; color:var(--text-secondary); border-top:1px solid var(--border); max-width:1200px; margin:0 auto; }}
        .footer a {{ color:var(--primary); text-decoration:none; }}
        .sidebar-info {{ display:grid; grid-template-columns:1fr 1fr; gap:16px; margin-top:16px; }}
        .info-card {{ background:var(--surface); border:1px solid var(--border); border-radius:var(--radius-lg); padding:16px; box-shadow:var(--shadow); }}
        .info-card h4 {{ font-size:12px; text-transform:uppercase; letter-spacing:.5px; color:var(--text-secondary); margin-bottom:8px; }}
        .info-card ul {{ list-style:none; font-size:13px; }}
        .info-card ul li {{ padding:4px 0; display:flex; align-items:center; gap:8px; }}
        .info-card ul li::before {{ content:''; width:6px; height:6px; border-radius:50%; background:var(--primary); flex-shrink:0; }}
        .chat-container {{ display:flex; flex-direction:column; height:520px; background:var(--surface); border:1px solid var(--border); border-radius:var(--radius-lg); box-shadow:var(--shadow); overflow:hidden; }}
        .chat-header {{ background:linear-gradient(135deg,#0078d4,#005a9e); color:white; padding:14px 20px; display:flex; justify-content:space-between; align-items:center; }}
        .chat-header h4 {{ font-size:14px; font-weight:600; margin:0; }}
        .chat-status {{ font-size:11px; display:flex; align-items:center; gap:6px; }}
        .chat-status .dot {{ width:8px; height:8px; border-radius:50%; }}
        .chat-messages {{ flex:1; overflow-y:auto; padding:16px; display:flex; flex-direction:column; gap:12px; background:var(--surface-alt); }}
        .chat-msg {{ max-width:80%; padding:10px 14px; border-radius:12px; font-size:13px; line-height:1.5; word-wrap:break-word; white-space:pre-wrap; }}
        .chat-msg.user {{ align-self:flex-end; background:var(--primary); color:white; border-bottom-right-radius:4px; }}
        .chat-msg.assistant {{ align-self:flex-start; background:var(--surface); border:1px solid var(--border); border-bottom-left-radius:4px; box-shadow:var(--shadow); }}
        .chat-msg.system {{ align-self:center; background:var(--surface-alt); border:1px solid var(--border); color:var(--text-secondary); font-size:12px; text-align:center; max-width:90%; }}
        .chat-input-bar {{ display:flex; gap:8px; padding:12px 16px; border-top:1px solid var(--border); background:var(--surface); }}
        .chat-input {{ flex:1; padding:10px 14px; border:1px solid var(--border); border-radius:20px; font-size:13px; outline:none; resize:none; font-family:inherit; }}
        .chat-input:focus {{ border-color:var(--primary); box-shadow:0 0 0 2px rgba(0,120,212,.15); }}
        .chat-send {{ padding:10px 20px; background:var(--primary); color:white; border:none; border-radius:20px; font-size:13px; font-weight:600; cursor:pointer; transition:background .15s; }}
        .chat-send:hover {{ background:var(--primary-dark); }}
        .chat-send:disabled {{ opacity:.5; cursor:not-allowed; }}
        .chat-upload-btn {{ display:flex; align-items:center; justify-content:center; width:38px; height:38px; border-radius:50%; border:1px solid var(--border); cursor:pointer; color:var(--text-secondary); transition:all .15s; flex-shrink:0; }}
        .chat-upload-btn:hover {{ background:var(--surface-alt); color:var(--primary); border-color:var(--primary); }}
        .chat-file-preview {{ display:flex; align-items:center; gap:8px; padding:8px 12px; margin:0 16px 4px; background:var(--surface-alt); border:1px solid var(--border); border-radius:var(--radius); font-size:12px; color:var(--text-secondary); }}
        .chat-file-preview .file-name {{ flex:1; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }}
        .chat-file-preview .file-remove {{ cursor:pointer; color:var(--danger); font-weight:bold; }}
        .chat-msg .file-analysis {{ background:var(--surface-alt); border:1px solid var(--border); border-radius:var(--radius); padding:10px; margin-top:8px; font-size:12px; white-space:pre-wrap; }}
        .chat-typing {{ display:flex; gap:4px; padding:8px 14px; align-self:flex-start; }}
        .chat-typing span {{ width:8px; height:8px; border-radius:50%; background:var(--text-secondary); animation:typing 1.4s infinite; }}
        .chat-typing span:nth-child(2) {{ animation-delay:.2s; }}
        .chat-typing span:nth-child(3) {{ animation-delay:.4s; }}
        @keyframes typing {{ 0%,60%,100%{{transform:translateY(0)}} 30%{{transform:translateY(-6px)}} }}
    </style>
</head>
<body>
    <nav class=\"topbar\">
        <div class=\"topbar-brand\">
            <svg viewBox=\"0 0 24 24\"><path d=\"M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5\"/></svg>
            {APP_NAME}
        </div>
        <div class=\"topbar-meta\">
            <div class=\"status-live\" id=\"health-indicator\"><span class=\"dot\"></span><span id=\"health-text\">Checking...</span></div>
            <span id=\"live-clock\" style=\"font-family:Consolas,monospace;font-size:12px;\"></span>
            <span class=\"env-badge\">prod</span>
            <span>eastus2</span>
        </div>
    </nav>
    <section class=\"hero\">
        <h1>{APP_NAME}</h1>
        <p>Build an enterprise-grade AI-powered smart city operations platform that orchestrates **9 distinct domain entities** across every supported data store (Cosmos DB, SQL, Blob Storage, Redis, AI Search, </p>
        <div class=\"hero-pills\">
            <span>v{VERSION}</span>
            <span>Container Apps</span>
            <span>eastus2</span>
        </div>
    </section>
    <div class=\"kpi-bar\">
        <div class=\"kpi\" id=\"kpi-incidents\"><div class=\"number\" id=\"count-incidents\">--</div><div class=\"label\">Total Incidents</div></div>
        <div class=\"kpi\" id=\"kpi-assets\"><div class=\"number\" id=\"count-assets\">--</div><div class=\"label\">Total Assets</div></div>
        <div class=\"kpi\" id=\"kpi-sensors\"><div class=\"number\" id=\"count-sensors\">--</div><div class=\"label\">Total Sensors</div></div>
        <div class=\"kpi\" id=\"kpi-service_requests\"><div class=\"number\" id=\"count-service_requests\">--</div><div class=\"label\">Total ServiceRequests</div></div>
        <div class=\"kpi\" id=\"kpi-transit_routes\"><div class=\"number\" id=\"count-transit_routes\">--</div><div class=\"label\">Total TransitRoutes</div></div>
        <div class=\"kpi\" id=\"kpi-vehicles\"><div class=\"number\" id=\"count-vehicles\">--</div><div class=\"label\">Total Vehicles</div></div>
        <div class=\"kpi\" id=\"kpi-zones\"><div class=\"number\" id=\"count-zones\">--</div><div class=\"label\">Total Zones</div></div>
        <div class=\"kpi\" id=\"kpi-work_orders\"><div class=\"number\" id=\"count-work_orders\">--</div><div class=\"label\">Total WorkOrders</div></div>
        <div class=\"kpi\" id=\"kpi-audit_logs\"><div class=\"number\" id=\"count-audit_logs\">--</div><div class=\"label\">Total AuditLogs</div></div>
        <div class=\"kpi warn\" id=\"kpi-action-needed\"><div class=\"number\" id=\"count-action-needed\">--</div><div class=\"label\">Needs Action</div></div>
        <div class=\"kpi ok\" id=\"kpi-resolved\"><div class=\"number\" id=\"count-resolved\">--</div><div class=\"label\">Resolved</div></div>
    </div>
    <div class=\"main\">
        <div class=\"tab-bar\">
            <div class=\"tab active\" data-tab=\"incidents\">Incidents</div>
            <div class=\"tab\" data-tab=\"assets\">Assets</div>
            <div class=\"tab\" data-tab=\"sensors\">Sensors</div>
            <div class=\"tab\" data-tab=\"service_requests\">ServiceRequests</div>
            <div class=\"tab\" data-tab=\"transit_routes\">TransitRoutes</div>
            <div class=\"tab\" data-tab=\"vehicles\">Vehicles</div>
            <div class=\"tab\" data-tab=\"zones\">Zones</div>
            <div class=\"tab\" data-tab=\"work_orders\">WorkOrders</div>
            <div class=\"tab\" data-tab=\"audit_logs\">AuditLogs</div>
            <div class=\"tab\" data-tab=\"system\">System</div>
            <div class=\"tab\" data-tab=\"ai-chat\">AI Assistant</div>
        </div>
        <div class=\"tab-panel active\" id=\"panel-incidents\"><div class=\"panel-toolbar\"><input type=\"text\" class=\"search-box\" placeholder=\"Search incidents...\" oninput=\"filterTable(&#39;incidents&#39;, this.value)\"><button class=\"btn btn-primary\" onclick=\"openCreateModal(&#39;Incident&#39;, &#39;incidents&#39;)\">+ New Incident</button></div><table class=\"data-table\" id=\"table-incidents\"><thead><tr><th>ID</th><th>Title</th><th>Description</th><th>Category</th><th>Severity</th><th>Status</th><th>Latitude</th><th>Longitude</th><th>Zone Id</th><th>Reporter Name</th><th>Reporter Phone</th><th>Affected Population</th><th>Estimated Damage</th><th>Ai Confidence</th><th>Ai Triage Notes</th><th>Photo Url</th><th>Audio Transcript</th><th>Resolution Notes</th><th>Response Time Minutes</th><th>Actions</th></tr></thead><tbody id=\"tbody-incidents\"><tr><td colspan=\"20\" style=\"text-align:center;padding:24px;color:var(--text-secondary)\">Loading...</td></tr></tbody></table></div>
        <div class=\"tab-panel\" id=\"panel-assets\"><div class=\"panel-toolbar\"><input type=\"text\" class=\"search-box\" placeholder=\"Search assets...\" oninput=\"filterTable(&#39;assets&#39;, this.value)\"><button class=\"btn btn-primary\" onclick=\"openCreateModal(&#39;Asset&#39;, &#39;assets&#39;)\">+ New Asset</button></div><table class=\"data-table\" id=\"table-assets\"><thead><tr><th>ID</th><th>Name</th><th>Asset Type</th><th>Status</th><th>Location Address</th><th>Latitude</th><th>Longitude</th><th>Zone Id</th><th>Install Date</th><th>Expected Lifespan Years</th><th>Manufacturer</th><th>Model Number</th><th>Last Inspection Date</th><th>Health Score</th><th>Replacement Cost</th><th>Maintenance Budget</th><th>Ai Failure Prediction</th><th>Ai Health Trend</th><th>Actions</th></tr></thead><tbody id=\"tbody-assets\"><tr><td colspan=\"19\" style=\"text-align:center;padding:24px;color:var(--text-secondary)\">Loading...</td></tr></tbody></table></div>
        <div class=\"tab-panel\" id=\"panel-sensors\"><div class=\"panel-toolbar\"><input type=\"text\" class=\"search-box\" placeholder=\"Search sensors...\" oninput=\"filterTable(&#39;sensors&#39;, this.value)\"><button class=\"btn btn-primary\" onclick=\"openCreateModal(&#39;Sensor&#39;, &#39;sensors&#39;)\">+ New Sensor</button></div><table class=\"data-table\" id=\"table-sensors\"><thead><tr><th>ID</th><th>Name</th><th>Sensor Type</th><th>Status</th><th>Latitude</th><th>Longitude</th><th>Zone Id</th><th>Asset Id</th><th>Vendor</th><th>Protocol</th><th>Last Reading Value</th><th>Last Reading Unit</th><th>Last Reading Timestamp</th><th>Threshold Min</th><th>Threshold Max</th><th>Alert Enabled</th><th>Battery Level</th><th>Firmware Version</th><th>Calibration Date</th><th>Actions</th></tr></thead><tbody id=\"tbody-sensors\"><tr><td colspan=\"20\" style=\"text-align:center;padding:24px;color:var(--text-secondary)\">Loading...</td></tr></tbody></table></div>
        <div class=\"tab-panel\" id=\"panel-service_requests\"><div class=\"panel-toolbar\"><input type=\"text\" class=\"search-box\" placeholder=\"Search servicerequests...\" oninput=\"filterTable(&#39;service_requests&#39;, this.value)\"><button class=\"btn btn-primary\" onclick=\"openCreateModal(&#39;ServiceRequest&#39;, &#39;service_requests&#39;)\">+ New ServiceRequest</button></div><table class=\"data-table\" id=\"table-service_requests\"><thead><tr><th>ID</th><th>Title</th><th>Description</th><th>Category</th><th>Priority</th><th>Status</th><th>Citizen Name</th><th>Citizen Email</th><th>Citizen Phone</th><th>Latitude</th><th>Longitude</th><th>Zone Id</th><th>Assigned Team</th><th>Estimated Completion Date</th><th>Ai Duplicate Score</th><th>Ai Category Confidence</th><th>Ai Suggested Resolution</th><th>Photo Url</th><th>Satisfaction Rating</th><th>Actions</th></tr></thead><tbody id=\"tbody-service_requests\"><tr><td colspan=\"20\" style=\"text-align:center;padding:24px;color:var(--text-secondary)\">Loading...</td></tr></tbody></table></div>
        <div class=\"tab-panel\" id=\"panel-transit_routes\"><div class=\"panel-toolbar\"><input type=\"text\" class=\"search-box\" placeholder=\"Search transitroutes...\" oninput=\"filterTable(&#39;transit_routes&#39;, this.value)\"><button class=\"btn btn-primary\" onclick=\"openCreateModal(&#39;TransitRoute&#39;, &#39;transit_routes&#39;)\">+ New TransitRoute</button></div><table class=\"data-table\" id=\"table-transit_routes\"><thead><tr><th>ID</th><th>Name</th><th>Route Number</th><th>Route Type</th><th>Status</th><th>Start Location</th><th>End Location</th><th>Total Stops</th><th>Daily Ridership</th><th>Average Delay Minutes</th><th>On Time Percentage</th><th>Fare Revenue Daily</th><th>Operating Cost Daily</th><th>Vehicle Count</th><th>Ai Demand Forecast</th><th>Ai Optimization Notes</th><th>Last Disruption Reason</th><th>Actions</th></tr></thead><tbody id=\"tbody-transit_routes\"><tr><td colspan=\"18\" style=\"text-align:center;padding:24px;color:var(--text-secondary)\">Loading...</td></tr></tbody></table></div>
        <div class=\"tab-panel\" id=\"panel-vehicles\"><div class=\"panel-toolbar\"><input type=\"text\" class=\"search-box\" placeholder=\"Search vehicles...\" oninput=\"filterTable(&#39;vehicles&#39;, this.value)\"><button class=\"btn btn-primary\" onclick=\"openCreateModal(&#39;Vehicle&#39;, &#39;vehicles&#39;)\">+ New Vehicle</button></div><table class=\"data-table\" id=\"table-vehicles\"><thead><tr><th>ID</th><th>Name</th><th>Vehicle Type</th><th>Status</th><th>License Plate</th><th>Vin Number</th><th>Current Latitude</th><th>Current Longitude</th><th>Assigned Department</th><th>Driver Name</th><th>Fuel Level Pct</th><th>Odometer Miles</th><th>Last Maintenance Date</th><th>Next Maintenance Due</th><th>Maintenance Cost Ytd</th><th>Ai Maintenance Prediction</th><th>Gps Speed Mph</th><th>Engine Health Score</th><th>Actions</th></tr></thead><tbody id=\"tbody-vehicles\"><tr><td colspan=\"19\" style=\"text-align:center;padding:24px;color:var(--text-secondary)\">Loading...</td></tr></tbody></table></div>
        <div class=\"tab-panel\" id=\"panel-zones\"><div class=\"panel-toolbar\"><input type=\"text\" class=\"search-box\" placeholder=\"Search zones...\" oninput=\"filterTable(&#39;zones&#39;, this.value)\"><button class=\"btn btn-primary\" onclick=\"openCreateModal(&#39;Zone&#39;, &#39;zones&#39;)\">+ New Zone</button></div><table class=\"data-table\" id=\"table-zones\"><thead><tr><th>ID</th><th>Name</th><th>Zone Code</th><th>Zone Type</th><th>Status</th><th>Population</th><th>Area Sq Miles</th><th>Council District</th><th>Active Incident Count</th><th>Active Sensor Count</th><th>Active Asset Count</th><th>Air Quality Index</th><th>Noise Level Db</th><th>Power Load Pct</th><th>Ai Risk Score</th><th>Ai Trend Summary</th><th>Actions</th></tr></thead><tbody id=\"tbody-zones\"><tr><td colspan=\"17\" style=\"text-align:center;padding:24px;color:var(--text-secondary)\">Loading...</td></tr></tbody></table></div>
        <div class=\"tab-panel\" id=\"panel-work_orders\"><div class=\"panel-toolbar\"><input type=\"text\" class=\"search-box\" placeholder=\"Search workorders...\" oninput=\"filterTable(&#39;work_orders&#39;, this.value)\"><button class=\"btn btn-primary\" onclick=\"openCreateModal(&#39;WorkOrder&#39;, &#39;work_orders&#39;)\">+ New WorkOrder</button></div><table class=\"data-table\" id=\"table-work_orders\"><thead><tr><th>ID</th><th>Title</th><th>Description</th><th>Work Type</th><th>Priority</th><th>Status</th><th>Asset Id</th><th>Assigned Team</th><th>Scheduled Date</th><th>Estimated Hours</th><th>Actual Hours</th><th>Parts Cost</th><th>Labor Cost</th><th>Total Cost</th><th>Ai Generated</th><th>Ai Justification</th><th>Completion Notes</th><th>Quality Rating</th><th>Actions</th></tr></thead><tbody id=\"tbody-work_orders\"><tr><td colspan=\"19\" style=\"text-align:center;padding:24px;color:var(--text-secondary)\">Loading...</td></tr></tbody></table></div>
        <div class=\"tab-panel\" id=\"panel-audit_logs\"><div class=\"panel-toolbar\"><input type=\"text\" class=\"search-box\" placeholder=\"Search auditlogs...\" oninput=\"filterTable(&#39;audit_logs&#39;, this.value)\"><button class=\"btn btn-primary\" onclick=\"openCreateModal(&#39;AuditLog&#39;, &#39;audit_logs&#39;)\">+ New AuditLog</button></div><table class=\"data-table\" id=\"table-audit_logs\"><thead><tr><th>ID</th><th>Event Type</th><th>Agent Name</th><th>User Id</th><th>User Role</th><th>Prompt Text</th><th>Completion Text</th><th>Token Count Prompt</th><th>Token Count Completion</th><th>Latency Ms</th><th>Model Name</th><th>Content Safety Result</th><th>Content Safety Categories</th><th>Pii Detected</th><th>Session Id</th><th>Correlation Id</th><th>Ip Address</th><th>Status</th><th>Actions</th></tr></thead><tbody id=\"tbody-audit_logs\"><tr><td colspan=\"19\" style=\"text-align:center;padding:24px;color:var(--text-secondary)\">Loading...</td></tr></tbody></table></div>
        <div class=\"tab-panel\" id=\"panel-system\"><div class=\"sidebar-info\"><div class=\"info-card\"><h4>Architecture</h4><ul><li>Compute: Container Apps</li><li>Data: Cosmos Db + Blob Storage + Sql + Redis + Ai Search + Table Storage</li><li>Security: Entra Id</li><li>Monitoring: Log Analytics</li></ul></div><div class=\"info-card\"><h4>API Documentation</h4><ul><li><a href=\"/docs\" style=\"color:var(--primary)\">Interactive API Docs</a></li><li><a href=\"/health\" style=\"color:var(--primary)\">Health Check</a></li><li><a href=\"/keyvault/status\" style=\"color:var(--primary)\">Key Vault Status</a></li></ul></div></div></div>
        <div class=\"tab-panel\" id=\"panel-ai-chat\"><div class=\"chat-container\"><div class=\"chat-header\"><h4>AI Assistant &mdash; smart-city-ai-operations-platform-extre</h4><div class=\"chat-status\"><span class=\"dot\" id=\"ai-status-dot\" style=\"background:var(--text-secondary)\"></span><span id=\"ai-status-text\">Checking...</span></div></div><div class=\"chat-messages\" id=\"chatMessages\"><div class=\"chat-msg system\">Ask me anything about your data. I can search, analyze, and provide insights across all entities.</div></div><div class=\"chat-input-bar\"><label class=\"chat-upload-btn\" title=\"Upload file (image, document, audio, receipt)\"><input type=\"file\" id=\"chatFileInput\" style=\"display:none\" onchange=\"uploadFile()\" accept=\"image/*,audio/*,.pdf,.docx,.xlsx,.csv,.txt,.json,.xml,.md,.html\"><svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M21.44 11.05l-9.19 9.19a6 6 0 01-8.49-8.49l9.19-9.19a4 4 0 015.66 5.66l-9.2 9.19a2 2 0 01-2.83-2.83l8.49-8.48\"/></svg></label><input type=\"text\" class=\"chat-input\" id=\"chatInput\" placeholder=\"Ask about your data or upload a file...\" onkeydown=\"if(event.key===&#39;Enter&#39;)sendChat()\"><button class=\"chat-send\" id=\"chatSend\" onclick=\"sendChat()\">Send</button></div></div></div>
    </div>
    <div class=\"modal-overlay\" id=\"createModal\">
        <div class=\"modal\">
            <div class=\"modal-header\"><h3 id=\"modalTitle\">Create</h3><button class=\"modal-close\" onclick=\"closeModal()\">&times;</button></div>
            <div class=\"modal-body\" id=\"modalBody\"></div>
            <div class=\"modal-footer\"><button class=\"btn\" onclick=\"closeModal()\">Cancel</button><button class=\"btn btn-primary\" id=\"modalSubmit\" onclick=\"submitCreate()\">Create</button></div>
        </div>
    </div>
    <div class=\"modal-overlay\" id=\"detailModal\">
        <div class=\"modal\">
            <div class=\"modal-header\"><h3 id=\"detailTitle\">Details</h3><button class=\"modal-close\" onclick=\"closeDetail()\">&times;</button></div>
            <div class=\"modal-body\" id=\"detailBody\"></div>
            <div class=\"modal-footer\" id=\"detailActions\"></div>
        </div>
    </div>
    <div id=\"toast\" class=\"toast\"></div>
    <footer class=\"footer\"><span id=\"last-updated\" style=\"margin-right:12px\"></span>{APP_NAME} v{VERSION} \u00b7 <a href=\"/docs\">API Docs</a> \u00b7 <button class=\"btn btn-primary btn-sm\" onclick=\"loadAll()\" style=\"margin-left:8px\">&#8635; Refresh Data</button> \u00b7 Enterprise DevEx Orchestrator</footer>
    <script>
        
        const ENTITIES = [
        {{
                "name": "Incident",
                "slug": "incidents",
                "id_field": "incident_id",
                "table_fields": [
                        "title",
                        "description",
                        "category",
                        "severity",
                        "status",
                        "latitude",
                        "longitude",
                        "zone_id",
                        "reporter_name",
                        "reporter_phone",
                        "affected_population",
                        "estimated_damage",
                        "ai_confidence",
                        "ai_triage_notes",
                        "photo_url",
                        "audio_transcript",
                        "resolution_notes",
                        "response_time_minutes"
                ],
                "form_fields": [
                        {{
                                "name": "title",
                                "type": "str"
                        }},
                        {{
                                "name": "description",
                                "type": "str"
                        }},
                        {{
                                "name": "category",
                                "type": "str"
                        }},
                        {{
                                "name": "severity",
                                "type": "str"
                        }},
                        {{
                                "name": "latitude",
                                "type": "float"
                        }},
                        {{
                                "name": "longitude",
                                "type": "float"
                        }},
                        {{
                                "name": "zone_id",
                                "type": "str"
                        }},
                        {{
                                "name": "reporter_name",
                                "type": "str"
                        }},
                        {{
                                "name": "reporter_phone",
                                "type": "str"
                        }},
                        {{
                                "name": "affected_population",
                                "type": "int"
                        }},
                        {{
                                "name": "estimated_damage",
                                "type": "float"
                        }},
                        {{
                                "name": "ai_confidence",
                                "type": "float"
                        }},
                        {{
                                "name": "ai_triage_notes",
                                "type": "str"
                        }},
                        {{
                                "name": "photo_url",
                                "type": "str"
                        }},
                        {{
                                "name": "audio_transcript",
                                "type": "str"
                        }},
                        {{
                                "name": "assigned_units",
                                "type": "list[str]"
                        }},
                        {{
                                "name": "resolution_notes",
                                "type": "str"
                        }},
                        {{
                                "name": "response_time_minutes",
                                "type": "float"
                        }}
                ],
                "actions": [
                        "triage",
                        "dispatch",
                        "escalate",
                        "resolve",
                        "correlate"
                ]
        }},
        {{
                "name": "Asset",
                "slug": "assets",
                "id_field": "asset_id",
                "table_fields": [
                        "name",
                        "asset_type",
                        "status",
                        "location_address",
                        "latitude",
                        "longitude",
                        "zone_id",
                        "install_date",
                        "expected_lifespan_years",
                        "manufacturer",
                        "model_number",
                        "last_inspection_date",
                        "health_score",
                        "replacement_cost",
                        "maintenance_budget",
                        "ai_failure_prediction",
                        "ai_health_trend"
                ],
                "form_fields": [
                        {{
                                "name": "name",
                                "type": "str"
                        }},
                        {{
                                "name": "asset_type",
                                "type": "str"
                        }},
                        {{
                                "name": "location_address",
                                "type": "str"
                        }},
                        {{
                                "name": "latitude",
                                "type": "float"
                        }},
                        {{
                                "name": "longitude",
                                "type": "float"
                        }},
                        {{
                                "name": "zone_id",
                                "type": "str"
                        }},
                        {{
                                "name": "install_date",
                                "type": "str"
                        }},
                        {{
                                "name": "expected_lifespan_years",
                                "type": "int"
                        }},
                        {{
                                "name": "manufacturer",
                                "type": "str"
                        }},
                        {{
                                "name": "model_number",
                                "type": "str"
                        }},
                        {{
                                "name": "last_inspection_date",
                                "type": "str"
                        }},
                        {{
                                "name": "health_score",
                                "type": "float"
                        }},
                        {{
                                "name": "replacement_cost",
                                "type": "float"
                        }},
                        {{
                                "name": "maintenance_budget",
                                "type": "float"
                        }},
                        {{
                                "name": "sensor_ids",
                                "type": "list[str]"
                        }},
                        {{
                                "name": "ai_failure_prediction",
                                "type": "str"
                        }},
                        {{
                                "name": "ai_health_trend",
                                "type": "str"
                        }}
                ],
                "actions": [
                        "predict",
                        "inspect",
                        "schedule_maintenance",
                        "decommission"
                ]
        }},
        {{
                "name": "Sensor",
                "slug": "sensors",
                "id_field": "sensor_id",
                "table_fields": [
                        "name",
                        "sensor_type",
                        "status",
                        "latitude",
                        "longitude",
                        "zone_id",
                        "asset_id",
                        "vendor",
                        "protocol",
                        "last_reading_value",
                        "last_reading_unit",
                        "last_reading_timestamp",
                        "threshold_min",
                        "threshold_max",
                        "alert_enabled",
                        "battery_level",
                        "firmware_version",
                        "calibration_date"
                ],
                "form_fields": [
                        {{
                                "name": "name",
                                "type": "str"
                        }},
                        {{
                                "name": "sensor_type",
                                "type": "str"
                        }},
                        {{
                                "name": "latitude",
                                "type": "float"
                        }},
                        {{
                                "name": "longitude",
                                "type": "float"
                        }},
                        {{
                                "name": "zone_id",
                                "type": "str"
                        }},
                        {{
                                "name": "asset_id",
                                "type": "str"
                        }},
                        {{
                                "name": "vendor",
                                "type": "str"
                        }},
                        {{
                                "name": "protocol",
                                "type": "str"
                        }},
                        {{
                                "name": "last_reading_value",
                                "type": "float"
                        }},
                        {{
                                "name": "last_reading_unit",
                                "type": "str"
                        }},
                        {{
                                "name": "last_reading_timestamp",
                                "type": "str"
                        }},
                        {{
                                "name": "threshold_min",
                                "type": "float"
                        }},
                        {{
                                "name": "threshold_max",
                                "type": "float"
                        }},
                        {{
                                "name": "alert_enabled",
                                "type": "bool"
                        }},
                        {{
                                "name": "battery_level",
                                "type": "float"
                        }},
                        {{
                                "name": "firmware_version",
                                "type": "str"
                        }},
                        {{
                                "name": "calibration_date",
                                "type": "str"
                        }}
                ],
                "actions": [
                        "calibrate",
                        "acknowledge_alert",
                        "disable"
                ]
        }},
        {{
                "name": "ServiceRequest",
                "slug": "service_requests",
                "id_field": "service_request_id",
                "table_fields": [
                        "title",
                        "description",
                        "category",
                        "priority",
                        "status",
                        "citizen_name",
                        "citizen_email",
                        "citizen_phone",
                        "latitude",
                        "longitude",
                        "zone_id",
                        "assigned_team",
                        "estimated_completion_date",
                        "ai_duplicate_score",
                        "ai_category_confidence",
                        "ai_suggested_resolution",
                        "photo_url",
                        "satisfaction_rating"
                ],
                "form_fields": [
                        {{
                                "name": "title",
                                "type": "str"
                        }},
                        {{
                                "name": "description",
                                "type": "str"
                        }},
                        {{
                                "name": "category",
                                "type": "str"
                        }},
                        {{
                                "name": "priority",
                                "type": "str"
                        }},
                        {{
                                "name": "citizen_name",
                                "type": "str"
                        }},
                        {{
                                "name": "citizen_email",
                                "type": "str"
                        }},
                        {{
                                "name": "citizen_phone",
                                "type": "str"
                        }},
                        {{
                                "name": "latitude",
                                "type": "float"
                        }},
                        {{
                                "name": "longitude",
                                "type": "float"
                        }},
                        {{
                                "name": "zone_id",
                                "type": "str"
                        }},
                        {{
                                "name": "assigned_team",
                                "type": "str"
                        }},
                        {{
                                "name": "estimated_completion_date",
                                "type": "str"
                        }},
                        {{
                                "name": "ai_duplicate_score",
                                "type": "float"
                        }},
                        {{
                                "name": "ai_category_confidence",
                                "type": "float"
                        }},
                        {{
                                "name": "ai_suggested_resolution",
                                "type": "str"
                        }},
                        {{
                                "name": "photo_url",
                                "type": "str"
                        }},
                        {{
                                "name": "satisfaction_rating",
                                "type": "int"
                        }}
                ],
                "actions": [
                        "acknowledge",
                        "assign",
                        "complete",
                        "reject",
                        "check_duplicate"
                ]
        }},
        {{
                "name": "TransitRoute",
                "slug": "transit_routes",
                "id_field": "transit_route_id",
                "table_fields": [
                        "name",
                        "route_number",
                        "route_type",
                        "status",
                        "start_location",
                        "end_location",
                        "total_stops",
                        "daily_ridership",
                        "average_delay_minutes",
                        "on_time_percentage",
                        "fare_revenue_daily",
                        "operating_cost_daily",
                        "vehicle_count",
                        "ai_demand_forecast",
                        "ai_optimization_notes",
                        "last_disruption_reason"
                ],
                "form_fields": [
                        {{
                                "name": "name",
                                "type": "str"
                        }},
                        {{
                                "name": "route_number",
                                "type": "str"
                        }},
                        {{
                                "name": "route_type",
                                "type": "str"
                        }},
                        {{
                                "name": "start_location",
                                "type": "str"
                        }},
                        {{
                                "name": "end_location",
                                "type": "str"
                        }},
                        {{
                                "name": "total_stops",
                                "type": "int"
                        }},
                        {{
                                "name": "daily_ridership",
                                "type": "int"
                        }},
                        {{
                                "name": "average_delay_minutes",
                                "type": "float"
                        }},
                        {{
                                "name": "on_time_percentage",
                                "type": "float"
                        }},
                        {{
                                "name": "fare_revenue_daily",
                                "type": "float"
                        }},
                        {{
                                "name": "operating_cost_daily",
                                "type": "float"
                        }},
                        {{
                                "name": "vehicle_count",
                                "type": "int"
                        }},
                        {{
                                "name": "zone_ids",
                                "type": "list[str]"
                        }},
                        {{
                                "name": "ai_demand_forecast",
                                "type": "str"
                        }},
                        {{
                                "name": "ai_optimization_notes",
                                "type": "str"
                        }},
                        {{
                                "name": "last_disruption_reason",
                                "type": "str"
                        }}
                ],
                "actions": [
                        "optimize",
                        "reroute",
                        "suspend",
                        "restore"
                ]
        }},
        {{
                "name": "Vehicle",
                "slug": "vehicles",
                "id_field": "vehicle_id",
                "table_fields": [
                        "name",
                        "vehicle_type",
                        "status",
                        "license_plate",
                        "vin_number",
                        "current_latitude",
                        "current_longitude",
                        "assigned_department",
                        "driver_name",
                        "fuel_level_pct",
                        "odometer_miles",
                        "last_maintenance_date",
                        "next_maintenance_due",
                        "maintenance_cost_ytd",
                        "ai_maintenance_prediction",
                        "gps_speed_mph",
                        "engine_health_score"
                ],
                "form_fields": [
                        {{
                                "name": "name",
                                "type": "str"
                        }},
                        {{
                                "name": "vehicle_type",
                                "type": "str"
                        }},
                        {{
                                "name": "license_plate",
                                "type": "str"
                        }},
                        {{
                                "name": "vin_number",
                                "type": "str"
                        }},
                        {{
                                "name": "current_latitude",
                                "type": "float"
                        }},
                        {{
                                "name": "current_longitude",
                                "type": "float"
                        }},
                        {{
                                "name": "assigned_department",
                                "type": "str"
                        }},
                        {{
                                "name": "driver_name",
                                "type": "str"
                        }},
                        {{
                                "name": "fuel_level_pct",
                                "type": "float"
                        }},
                        {{
                                "name": "odometer_miles",
                                "type": "int"
                        }},
                        {{
                                "name": "last_maintenance_date",
                                "type": "str"
                        }},
                        {{
                                "name": "next_maintenance_due",
                                "type": "str"
                        }},
                        {{
                                "name": "maintenance_cost_ytd",
                                "type": "float"
                        }},
                        {{
                                "name": "ai_maintenance_prediction",
                                "type": "str"
                        }},
                        {{
                                "name": "gps_speed_mph",
                                "type": "float"
                        }},
                        {{
                                "name": "engine_health_score",
                                "type": "float"
                        }}
                ],
                "actions": [
                        "deploy",
                        "recall",
                        "refuel",
                        "schedule_maintenance"
                ]
        }},
        {{
                "name": "Zone",
                "slug": "zones",
                "id_field": "zone_id",
                "table_fields": [
                        "name",
                        "zone_code",
                        "zone_type",
                        "status",
                        "population",
                        "area_sq_miles",
                        "council_district",
                        "active_incident_count",
                        "active_sensor_count",
                        "active_asset_count",
                        "air_quality_index",
                        "noise_level_db",
                        "power_load_pct",
                        "ai_risk_score",
                        "ai_trend_summary"
                ],
                "form_fields": [
                        {{
                                "name": "name",
                                "type": "str"
                        }},
                        {{
                                "name": "zone_code",
                                "type": "str"
                        }},
                        {{
                                "name": "zone_type",
                                "type": "str"
                        }},
                        {{
                                "name": "population",
                                "type": "int"
                        }},
                        {{
                                "name": "area_sq_miles",
                                "type": "float"
                        }},
                        {{
                                "name": "council_district",
                                "type": "int"
                        }},
                        {{
                                "name": "emergency_contacts",
                                "type": "list[str]"
                        }},
                        {{
                                "name": "active_incident_count",
                                "type": "int"
                        }},
                        {{
                                "name": "active_sensor_count",
                                "type": "int"
                        }},
                        {{
                                "name": "active_asset_count",
                                "type": "int"
                        }},
                        {{
                                "name": "air_quality_index",
                                "type": "float"
                        }},
                        {{
                                "name": "noise_level_db",
                                "type": "float"
                        }},
                        {{
                                "name": "power_load_pct",
                                "type": "float"
                        }},
                        {{
                                "name": "ai_risk_score",
                                "type": "float"
                        }},
                        {{
                                "name": "ai_trend_summary",
                                "type": "str"
                        }}
                ],
                "actions": [
                        "alert",
                        "evacuate",
                        "clear"
                ]
        }},
        {{
                "name": "WorkOrder",
                "slug": "work_orders",
                "id_field": "work_order_id",
                "table_fields": [
                        "title",
                        "description",
                        "work_type",
                        "priority",
                        "status",
                        "asset_id",
                        "assigned_team",
                        "scheduled_date",
                        "estimated_hours",
                        "actual_hours",
                        "parts_cost",
                        "labor_cost",
                        "total_cost",
                        "ai_generated",
                        "ai_justification",
                        "completion_notes",
                        "quality_rating"
                ],
                "form_fields": [
                        {{
                                "name": "title",
                                "type": "str"
                        }},
                        {{
                                "name": "description",
                                "type": "str"
                        }},
                        {{
                                "name": "work_type",
                                "type": "str"
                        }},
                        {{
                                "name": "priority",
                                "type": "str"
                        }},
                        {{
                                "name": "asset_id",
                                "type": "str"
                        }},
                        {{
                                "name": "assigned_team",
                                "type": "str"
                        }},
                        {{
                                "name": "scheduled_date",
                                "type": "str"
                        }},
                        {{
                                "name": "estimated_hours",
                                "type": "float"
                        }},
                        {{
                                "name": "actual_hours",
                                "type": "float"
                        }},
                        {{
                                "name": "parts_cost",
                                "type": "float"
                        }},
                        {{
                                "name": "labor_cost",
                                "type": "float"
                        }},
                        {{
                                "name": "total_cost",
                                "type": "float"
                        }},
                        {{
                                "name": "ai_generated",
                                "type": "bool"
                        }},
                        {{
                                "name": "ai_justification",
                                "type": "str"
                        }},
                        {{
                                "name": "completion_notes",
                                "type": "str"
                        }},
                        {{
                                "name": "quality_rating",
                                "type": "int"
                        }}
                ],
                "actions": [
                        "approve",
                        "schedule",
                        "start",
                        "complete",
                        "cancel"
                ]
        }},
        {{
                "name": "AuditLog",
                "slug": "audit_logs",
                "id_field": "audit_log_id",
                "table_fields": [
                        "event_type",
                        "agent_name",
                        "user_id",
                        "user_role",
                        "prompt_text",
                        "completion_text",
                        "token_count_prompt",
                        "token_count_completion",
                        "latency_ms",
                        "model_name",
                        "content_safety_result",
                        "content_safety_categories",
                        "pii_detected",
                        "session_id",
                        "correlation_id",
                        "ip_address",
                        "status"
                ],
                "form_fields": [
                        {{
                                "name": "event_type",
                                "type": "str"
                        }},
                        {{
                                "name": "agent_name",
                                "type": "str"
                        }},
                        {{
                                "name": "user_id",
                                "type": "str"
                        }},
                        {{
                                "name": "user_role",
                                "type": "str"
                        }},
                        {{
                                "name": "prompt_text",
                                "type": "str"
                        }},
                        {{
                                "name": "completion_text",
                                "type": "str"
                        }},
                        {{
                                "name": "token_count_prompt",
                                "type": "int"
                        }},
                        {{
                                "name": "token_count_completion",
                                "type": "int"
                        }},
                        {{
                                "name": "latency_ms",
                                "type": "int"
                        }},
                        {{
                                "name": "model_name",
                                "type": "str"
                        }},
                        {{
                                "name": "content_safety_result",
                                "type": "str"
                        }},
                        {{
                                "name": "content_safety_categories",
                                "type": "str"
                        }},
                        {{
                                "name": "pii_detected",
                                "type": "bool"
                        }},
                        {{
                                "name": "session_id",
                                "type": "str"
                        }},
                        {{
                                "name": "correlation_id",
                                "type": "str"
                        }},
                        {{
                                "name": "ip_address",
                                "type": "str"
                        }}
                ],
                "actions": []
        }}
];
        let allData = {{}};

        // Dynamic status classification — adapts to any domain
        const ACTION_STATUSES = ['pending','draft','new','open','queued','submitted','waiting','in_progress','in-progress','processing','running','active','review','pending_review','on_hold','on-hold','paused'];
        const RESOLVED_STATUSES = ['completed','approved','processed','done','resolved','closed','success','passed','delivered','published','inactive','disabled','offline','cancelled','rejected','failed','error','denied','expired','terminated'];

        async function loadAll() {{
            let actionNeeded = 0, resolved = 0;
            for (const ent of ENTITIES) {{
                try {{
                    const r = await fetch('/api/v1/' + ent.slug);
                    const d = await r.json();
                    const rows = Array.isArray(d) ? d : (d.value || d.items || d.data || []);
                    allData[ent.slug] = rows;
                    document.getElementById('count-' + ent.slug).textContent = rows.length;
                    rows.forEach(row => {{
                        const s = String(row.status || '').toLowerCase().replace(/ /g,'_');
                        if (ACTION_STATUSES.includes(s)) actionNeeded++;
                        else if (RESOLVED_STATUSES.includes(s)) resolved++;
                    }});
                    renderTable(ent, rows);
                }} catch(e) {{
                    console.error('Failed to load ' + ent.slug, e);
                    document.getElementById('count-' + ent.slug).textContent = '!';
                }}
            }}
            const anEl = document.getElementById('count-action-needed');
            if (anEl) anEl.textContent = actionNeeded;
            const rsEl = document.getElementById('count-resolved');
            if (rsEl) rsEl.textContent = resolved;
            const luEl = document.getElementById('last-updated');
            if (luEl) luEl.textContent = 'Last updated: ' + new Date().toLocaleTimeString();
        }}

        function renderTable(ent, rows) {{
            const tbody = document.getElementById('tbody-' + ent.slug);
            if (!rows.length) {{
                tbody.innerHTML = '<tr><td colspan="' + (ent.table_fields.length + 2) + '" style="text-align:center;padding:32px;color:var(--text-secondary)"><div class="empty-state"><div class="icon">📭</div><div>No ' + ent.slug.replace(/_/g,' ') + ' yet</div></div></td></tr>';
                return;
            }}
            tbody.innerHTML = rows.map(row => {{
                const idShort = (row.id || '').substring(0, 8);
                let cells = '<td style="font-family:Consolas,monospace;font-size:12px;cursor:pointer;color:var(--primary)" onclick="openDetail(&#39;' + ent.slug + '&#39;,&#39;' + row.id + '&#39;)">' + idShort + '...</td>';
                ent.table_fields.forEach(f => {{
                    const val = row[f] != null ? row[f] : '-';
                    if (f === 'status' || f === 'state' || f.endsWith('_status')) {{
                        cells += '<td><span class="badge badge-' + String(val).replace(/ /g,'-').replace(/[^a-zA-Z0-9-_]/g,'') + '">' + val + '</span></td>';
                    }} else if (f.endsWith('_at') || f.endsWith('_date') || f === 'timestamp' || f === 'date' || f === 'created' || f === 'updated') {{
                        const d = new Date(val);
                        cells += '<td>' + (isNaN(d) ? val : d.toLocaleDateString()) + '</td>';
                    }} else if (f === 'amount' || f === 'price' || f === 'cost' || f === 'total' || f === 'fee' || f === 'balance' || f.endsWith('_amount') || f.endsWith('_price') || f.endsWith('_cost')) {{
                        cells += '<td style="font-weight:600">$' + Number(val).toFixed(2) + '</td>';
                    }} else if (f === 'priority' || f === 'severity' || f === 'level' || f === 'urgency') {{
                        const pcolor = ['high','critical','urgent','p1'].includes(String(val).toLowerCase()) ? 'var(--danger)' : ['medium','p2','warning'].includes(String(val).toLowerCase()) ? 'var(--warning)' : 'var(--text-secondary)';
                        cells += '<td style="font-weight:600;color:' + pcolor + '">' + val + '</td>';
                    }} else if (f === 'email' || f.endsWith('_email')) {{
                        cells += '<td><a href="mailto:' + val + '" style="color:var(--primary)">' + val + '</a></td>';
                    }} else if (f === 'url' || f === 'link' || f === 'website' || f.endsWith('_url')) {{
                        cells += '<td><a href="' + val + '" target="_blank" style="color:var(--primary)">' + String(val).substring(0,40) + '</a></td>';
                    }} else if (typeof val === 'boolean' || f.startsWith('is_') || f.startsWith('has_') || f === 'enabled' || f === 'active') {{
                        cells += '<td>' + (val === true || val === 'true' || val === 'True' ? '✅' : '❌') + '</td>';
                    }} else if (typeof val === 'number' && !Number.isInteger(val)) {{
                        cells += '<td>' + Number(val).toFixed(2) + '</td>';
                    }} else {{
                        const sv = String(val);
                        cells += '<td>' + (sv.length > 60 ? sv.substring(0,57) + '...' : sv) + '</td>';
                    }}
                }});
                let actionBtns = '';
                const ACTION_STYLES = {{'approve':'btn-success','accept':'btn-success','activate':'btn-success','enable':'btn-success','publish':'btn-success','start':'btn-success','deploy':'btn-success','confirm':'btn-success','resolve':'btn-success',
                    'reject':'btn-danger','deny':'btn-danger','delete':'btn-danger','remove':'btn-danger','cancel':'btn-danger','terminate':'btn-danger','disable':'btn-danger','block':'btn-danger','revoke':'btn-danger',
                    'process':'btn-warning','escalate':'btn-warning','retry':'btn-warning','resubmit':'btn-warning','pause':'btn-warning','suspend':'btn-warning','flag':'btn-warning','review':'btn-warning','archive':'btn-warning'}};
                const s = String(row.status || '').toLowerCase().replace(/ /g,'_');
                const isTerminal = RESOLVED_STATUSES.includes(s);
                if (!isTerminal) {{
                    ent.actions.forEach(action => {{
                        const btnClass = ACTION_STYLES[action] || 'btn-primary';
                        const label = action.charAt(0).toUpperCase() + action.slice(1).replace(/_/g,' ');
                        actionBtns += '<button class="btn ' + btnClass + ' btn-sm" onclick="doAction(&#39;' + ent.slug + '&#39;,&#39;' + row.id + '&#39;,&#39;' + action + '&#39;)">' + label + '</button> ';
                    }});
                }}
                if (!actionBtns) actionBtns = '<span style="color:var(--text-secondary);font-size:12px">' + (isTerminal ? '✔ Done' : 'No actions') + '</span>';
                cells += '<td>' + actionBtns + '</td>';
                return '<tr>' + cells + '</tr>';
            }}).join('');
        }}

        function filterTable(slug, query) {{
            const rows = allData[slug] || [];
            const q = query.toLowerCase();
            const ent = ENTITIES.find(e => e.slug === slug);
            const filtered = rows.filter(r => JSON.stringify(r).toLowerCase().includes(q));
            renderTable(ent, filtered);
        }}

        // Tabs
        document.querySelectorAll('.tab').forEach(tab => {{
            tab.addEventListener('click', () => {{
                document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
                document.querySelectorAll('.tab-panel').forEach(p => p.classList.remove('active'));
                tab.classList.add('active');
                document.getElementById('panel-' + tab.dataset.tab).classList.add('active');
            }});
        }});

        // Create modal
        let createTarget = {{}};
        function openCreateModal(entityName, slug) {{
            const ent = ENTITIES.find(e => e.slug === slug);
            createTarget = {{ entityName, slug }};
            document.getElementById('modalTitle').textContent = 'Create New ' + entityName;
            let formHtml = '';
            ent.form_fields.forEach(f => {{
                const label = f.name.replace(/_/g, ' ');
                if (f.type === 'list' || f.type === 'list[str]') {{
                    formHtml += '<div class="form-group"><label>' + label + '</label><input type="text" name="' + f.name + '" placeholder="Comma-separated values"></div>';
                }} else if (f.type === 'float' || f.type === 'int') {{
                    formHtml += '<div class="form-group"><label>' + label + '</label><input type="number" name="' + f.name + '" step="any"></div>';
                }} else if (f.type === 'bool') {{
                    formHtml += '<div class="form-group"><label>' + label + '</label><select name="' + f.name + '"><option value="true">Yes</option><option value="false">No</option></select></div>';
                }} else {{
                    formHtml += '<div class="form-group"><label>' + label + '</label><input type="text" name="' + f.name + '"></div>';
                }}
            }});
            document.getElementById('modalBody').innerHTML = formHtml;
            document.getElementById('createModal').classList.add('open');
        }}
        function closeModal() {{ document.getElementById('createModal').classList.remove('open'); }}

        async function submitCreate() {{
            const ent = ENTITIES.find(e => e.slug === createTarget.slug);
            const body = {{}};
            ent.form_fields.forEach(f => {{
                const input = document.querySelector('#modalBody [name="' + f.name + '"]');
                if (!input) return;
                let val = input.value;
                if (f.type === 'list' || f.type === 'list[str]') {{
                    body[f.name] = val ? val.split(',').map(s => s.trim()) : [];
                }} else if (f.type === 'float') {{
                    body[f.name] = parseFloat(val) || 0;
                }} else if (f.type === 'int') {{
                    body[f.name] = parseInt(val) || 0;
                }} else if (f.type === 'bool') {{
                    body[f.name] = val === 'true';
                }} else {{
                    body[f.name] = val;
                }}
            }});
            try {{
                const r = await fetch('/api/v1/' + createTarget.slug, {{ method:'POST', headers:{{'Content-Type':'application/json'}}, body:JSON.stringify(body) }});
                if (r.ok) {{
                    showToast('success', createTarget.entityName + ' created successfully');
                    closeModal();
                    loadAll();
                }} else {{
                    const err = await r.json();
                    showToast('error', 'Error: ' + (err.detail || JSON.stringify(err)));
                }}
            }} catch(e) {{
                showToast('error', 'Network error');
            }}
        }}

        // Detail modal
        function openDetail(slug, id) {{
            const ent = ENTITIES.find(e => e.slug === slug);
            const rows = allData[slug] || [];
            const row = rows.find(r => r.id === id);
            if (!row) return;
            document.getElementById('detailTitle').textContent = ent.name + ' Details';
            let html = '';
            Object.entries(row).forEach(([k,v]) => {{
                const label = k.replace(/_/g,' ').replace(/\\b\\w/g, c => c.toUpperCase());
                let display = v;
                if (Array.isArray(v)) display = v.join(', ');
                if (k === 'status' || k === 'state' || k.endsWith('_status')) display = '<span class="badge badge-' + String(v).replace(/ /g,'-').replace(/[^a-zA-Z0-9_-]/g,'') + '">' + v + '</span>';
                else if (k === 'amount' || k === 'price' || k === 'cost' || k === 'total' || k === 'fee' || k === 'balance' || k.endsWith('_amount') || k.endsWith('_price') || k.endsWith('_cost')) display = '$' + Number(v).toFixed(2);
                else if (k.endsWith('_at') || k.endsWith('_date') || k === 'timestamp' || k === 'date') {{ const d=new Date(v); if(!isNaN(d)) display=d.toLocaleString(); }}
                else if (typeof v === 'boolean' || k.startsWith('is_') || k.startsWith('has_')) display = v ? '✅' : '❌';
                else if (k === 'email' || k.endsWith('_email')) display = '<a href="mailto:'+v+'" style="color:var(--primary)">'+v+'</a>';
                html += '<div class="detail-row"><div class="dl">' + label + '</div><div>' + display + '</div></div>';
            }});
            document.getElementById('detailBody').innerHTML = html;

            // Action buttons in detail — dynamic from entity actions
            let actionsHtml = '<button class="btn" onclick="closeDetail()">Close</button>';
            const ds = String(row.status || '').toLowerCase().replace(/ /g,'_');
            const isTerminalDetail = RESOLVED_STATUSES.includes(ds);
            if (!isTerminalDetail) {{
                const DA = {{'approve':'btn-success','accept':'btn-success','activate':'btn-success','enable':'btn-success','publish':'btn-success','start':'btn-success','confirm':'btn-success','resolve':'btn-success',
                    'reject':'btn-danger','deny':'btn-danger','delete':'btn-danger','remove':'btn-danger','cancel':'btn-danger','terminate':'btn-danger','disable':'btn-danger',
                    'process':'btn-warning','escalate':'btn-warning','retry':'btn-warning','resubmit':'btn-warning','pause':'btn-warning','review':'btn-warning','archive':'btn-warning'}};
                ent.actions.forEach(action => {{
                    const bc = DA[action] || 'btn-primary';
                    const lbl = action.charAt(0).toUpperCase() + action.slice(1).replace(/_/g,' ');
                    actionsHtml += ' <button class="btn ' + bc + '" onclick="doAction(&#39;' + slug + '&#39;,&#39;' + id + '&#39;,&#39;' + action + '&#39;);closeDetail()">' + lbl + '</button>';
                }});
            }}
            document.getElementById('detailActions').innerHTML = actionsHtml;
            document.getElementById('detailModal').classList.add('open');
        }}
        function closeDetail() {{ document.getElementById('detailModal').classList.remove('open'); }}

        async function doAction(slug, id, action) {{
            if (!confirm('Are you sure you want to ' + action + ' this record?')) return;
            try {{
                const r = await fetch('/api/v1/' + slug + '/' + id + '/' + action, {{ method:'POST' }});
                if (r.ok) {{
                    showToast('success', action.charAt(0).toUpperCase() + action.slice(1) + ' completed');
                    loadAll();
                }} else {{
                    const err = await r.json();
                    showToast('error', 'Error: ' + (err.detail || 'Action failed'));
                }}
            }} catch(e) {{
                showToast('error', 'Network error');
            }}
        }}

        function showToast(type, msg) {{
            const t = document.getElementById('toast');
            t.textContent = msg;
            t.className = 'toast ' + type + ' show';
            setTimeout(() => {{ t.classList.remove('show'); }}, 3000);
        }}

        // Init
        loadAll();
        setInterval(loadAll, 30000);

        // Real-time clock
        function updateClock() {{
            const now = new Date();
            const el = document.getElementById('live-clock');
            if (el) el.textContent = now.toLocaleString('en-US', {{
                weekday:'short', year:'numeric', month:'short', day:'numeric',
                hour:'2-digit', minute:'2-digit', second:'2-digit', hour12:false
            }});
        }}
        updateClock();
        setInterval(updateClock, 1000);

        // Health check
        async function checkHealth() {{
            const indicator = document.getElementById('health-indicator');
            if (!indicator) return;
            const dot = indicator.querySelector('.dot');
            const text = document.getElementById('health-text');
            try {{
                const r = await fetch('/health');
                const d = await r.json();
                if (d.status === 'healthy') {{
                    dot.style.background = 'var(--success)';
                    text.textContent = 'Healthy';
                }} else {{
                    dot.style.background = 'var(--warning)';
                    text.textContent = 'Degraded';
                }}
            }} catch(e) {{
                dot.style.background = 'var(--danger)';
                text.textContent = 'Offline';
            }}
        }}
        checkHealth();
        setInterval(checkHealth, 15000);


        // AI Chat
        let chatHistory = [];
        async function checkAIStatus() {{
            const dot = document.getElementById('ai-status-dot');
            const text = document.getElementById('ai-status-text');
            if (!dot) return;
            try {{
                const r = await fetch('/api/v1/ai/models');
                const d = await r.json();
                if (d.status === 'available') {{
                    dot.style.background = 'var(--success)';
                    text.textContent = d.provider + ' (' + d.chat_model + ')';
                }} else {{
                    dot.style.background = 'var(--warning)';
                    text.textContent = 'Not configured';
                }}
            }} catch(e) {{
                dot.style.background = 'var(--danger)';
                text.textContent = 'Unavailable';
            }}
        }}
        checkAIStatus();

        function appendChatMsg(role, content) {{
            const container = document.getElementById('chatMessages');
            const div = document.createElement('div');
            div.className = 'chat-msg ' + role;
            div.textContent = content;
            container.appendChild(div);
            container.scrollTop = container.scrollHeight;
        }}

        function showTyping() {{
            const container = document.getElementById('chatMessages');
            const div = document.createElement('div');
            div.className = 'chat-typing';
            div.id = 'typing-indicator';
            div.innerHTML = '<span></span><span></span><span></span>';
            container.appendChild(div);
            container.scrollTop = container.scrollHeight;
        }}

        function hideTyping() {{
            const el = document.getElementById('typing-indicator');
            if (el) el.remove();
        }}

        async function sendChat() {{
            const input = document.getElementById('chatInput');
            const msg = input.value.trim();
            if (!msg) return;
            input.value = '';
            appendChatMsg('user', msg);
            chatHistory.push({{ role: 'user', content: msg }});
            document.getElementById('chatSend').disabled = true;
            showTyping();
            try {{
                const r = await fetch('/api/v1/ai/chat', {{
                    method: 'POST',
                    headers: {{ 'Content-Type': 'application/json' }},
                    body: JSON.stringify({{
                        message: msg,
                        history: chatHistory.slice(-10)
                    }})
                }});
                hideTyping();
                if (r.ok) {{
                    const d = await r.json();
                    appendChatMsg('assistant', d.reply);
                    chatHistory.push({{ role: 'assistant', content: d.reply }});
                }} else {{
                    const err = await r.json().catch(() => ({{}}));
                    appendChatMsg('system', 'Error: ' + (err.detail || 'AI service unavailable. Configure AZURE_OPENAI_ENDPOINT or OPENAI_API_KEY.'));
                }}
            }} catch(e) {{
                hideTyping();
                appendChatMsg('system', 'Network error: ' + e.message);
            }}
            document.getElementById('chatSend').disabled = false;
            input.focus();
        }}

        async function uploadFile() {{
            const fileInput = document.getElementById('chatFileInput');
            const file = fileInput.files[0];
            if (!file) return;
            fileInput.value = '';

            const sizeMB = file.size / (1024 * 1024);
            if (sizeMB > 20) {{
                appendChatMsg('system', 'File too large (max 20MB): ' + file.name);
                return;
            }}

            appendChatMsg('user', '📎 Uploaded: ' + file.name + ' (' + (sizeMB < 1 ? (file.size/1024).toFixed(0)+'KB' : sizeMB.toFixed(1)+'MB') + ')');
            document.getElementById('chatSend').disabled = true;
            showTyping();

            try {{
                const formData = new FormData();
                formData.append('file', file);

                const r = await fetch('/api/v1/ai/upload', {{
                    method: 'POST',
                    body: formData
                }});
                hideTyping();
                if (r.ok) {{
                    const d = await r.json();
                    const replyText = d.analysis || d.reply || 'File processed.';
                    appendChatMsg('assistant', replyText);
                    chatHistory.push({{ role: 'user', content: 'Uploaded file: ' + file.name }});
                    chatHistory.push({{ role: 'assistant', content: replyText }});
                }} else {{
                    const err = await r.json().catch(() => ({{}}));
                    appendChatMsg('system', 'Upload error: ' + (err.detail || 'Failed to process file'));
                }}
            }} catch(e) {{
                hideTyping();
                appendChatMsg('system', 'Upload failed: ' + e.message);
            }}
            document.getElementById('chatSend').disabled = false;
        }}

    </script>
</body>
</html>
"""
    return HTMLResponse(content=html)


# -- Key Vault Status ------------------------------------------------
@app.get("/keyvault/status")
async def keyvault_status():
    """Check Key Vault connectivity via Managed Identity."""
    try:
        client = get_keyvault_client()
        # List secrets to verify access (limited to 1)
        secrets = list(client.list_properties_of_secrets(max_page_size=1))
        return {
            "status": "connected",
            "vault_accessible": True,
        }
    except Exception as e:
        logger.error(f"Key Vault health check failed: {e}")
        return JSONResponse(
            status_code=503,
            content={"status": "error", "detail": str(e)},
        )



@app.get("/storage/status")
async def storage_status():
    """Check storage account connectivity."""
    try:
        client = get_blob_client()
        containers = list(client.list_containers(max_results=1))
        return {
            "status": "connected",
            "containers_accessible": True,
        }
    except Exception as e:
        logger.error(f"Storage health check failed: {e}")
        return JSONResponse(
            status_code=503,
            content={"status": "error", "detail": str(e)},
        )

# -- Startup Event ----------------------------------------------------
@app.on_event("startup")
async def startup():
    """Application startup tasks."""
    logger.info(f"{APP_NAME} v{VERSION} starting up")
    logger.info(f"Environment: {os.getenv('ENVIRONMENT', 'unknown')}")


@app.on_event("shutdown")
async def shutdown():
    """Application shutdown tasks."""
    logger.info(f"{APP_NAME} shutting down")


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", "8000"))
    uvicorn.run(app, host="0.0.0.0", port=port)
