"""Test Generator -- produces pytest tests for the scaffolded application.

Generates comprehensive test suites including:
    - Unit tests for API endpoints
    - Integration tests for Key Vault / Storage
    - Security tests (auth, headers, input validation)
    - Health check tests
    - Configuration tests
"""

from __future__ import annotations

from src.orchestrator.intent_schema import DataStore, IntentSpec
from src.orchestrator.generators.route_manifest import RouteAction, RouteBuilder
from src.orchestrator.logging import get_logger

logger = get_logger(__name__)


def _route_path_with_id(path_template: str, entity_snake: str) -> str:
    """Replace {entity_id} in route path with a known seed ID."""
    import re
    return re.sub(r"\{[^}]+\}", f"{entity_snake}-001", path_template)


def _route_path_404(path_template: str) -> str:
    """Replace {entity_id} with a nonexistent ID."""
    import re
    return re.sub(r"\{[^}]+\}", "nonexistent-id-999", path_template)


class TestGenerator:
    """Generates pytest test files for the scaffolded application."""

    def generate(self, spec: IntentSpec) -> dict[str, str]:
        """Generate test files for the application.

        Args:
            spec: The parsed intent specification.

        Returns:
            Mapping of file path -> content.
        """
        logger.info("test_generator.start", project=spec.project_name)

        files: dict[str, str] = {}

        files["tests/conftest.py"] = self._conftest(spec)
        files["tests/__init__.py"] = '"""Generated test package."""\n'
        files["tests/test_health.py"] = self._test_health(spec)
        files["tests/test_api.py"] = self._test_api(spec)
        files["tests/test_security.py"] = self._test_security(spec)
        files["tests/test_config.py"] = self._test_config(spec)

        if DataStore.BLOB_STORAGE in spec.data_stores:
            files["tests/test_storage.py"] = self._test_storage(spec)

        # Route-manifest-driven entity CRUD tests
        if spec.entities:
            files["tests/test_entity_crud.py"] = self._test_entity_crud(spec)

        files["tests/requirements-test.txt"] = self._test_requirements()

        logger.info("test_generator.complete", file_count=len(files))
        return files

    def _conftest(self, spec: IntentSpec) -> str:
        return f'''"""Pytest configuration and shared fixtures.

Project: {spec.project_name}
Generated by: Enterprise DevEx Orchestrator Agent
"""

from __future__ import annotations

import os
from unittest.mock import MagicMock, patch

import pytest
from fastapi.testclient import TestClient


@pytest.fixture(autouse=True)
def _env_setup(monkeypatch: pytest.MonkeyPatch) -> None:
    """Set required environment variables for all tests."""
    monkeypatch.setenv("KEY_VAULT_NAME", "kv-test-vault")
    monkeypatch.setenv("KEY_VAULT_URI", "https://kv-test-vault.vault.azure.net")
    monkeypatch.setenv("AZURE_CLIENT_ID", "00000000-0000-0000-0000-000000000000")
    monkeypatch.setenv("ENVIRONMENT", "test")
    monkeypatch.setenv("PORT", "8000")
    monkeypatch.setenv("STORAGE_ACCOUNT_URL", "https://testaccount.blob.core.windows.net")


@pytest.fixture
def mock_credential() -> MagicMock:
    """Mock DefaultAzureCredential."""
    with patch("src.app.main.DefaultAzureCredential") as mock:
        yield mock.return_value


@pytest.fixture
def mock_keyvault(mock_credential: MagicMock) -> MagicMock:
    """Mock SecretClient for Key Vault tests."""
    with patch("src.app.main.SecretClient") as mock:
        instance = mock.return_value
        instance.list_properties_of_secrets.return_value = []
        yield instance


@pytest.fixture
def client() -> TestClient:
    """Create FastAPI test client."""
    from src.app.main import app

    return TestClient(app)
'''

    def _test_health(self, spec: IntentSpec) -> str:
        return f'''"""Health endpoint tests.

Project: {spec.project_name}
"""

from __future__ import annotations

from fastapi.testclient import TestClient


class TestHealthEndpoint:
    """Tests for /health endpoint."""

    def test_health_returns_200(self, client: TestClient) -> None:
        """Health endpoint returns 200 OK."""
        response = client.get("/health")
        assert response.status_code == 200

    def test_health_response_structure(self, client: TestClient) -> None:
        """Health response contains required fields."""
        response = client.get("/health")
        data = response.json()
        assert "status" in data
        assert "service" in data
        assert "version" in data
        assert "timestamp" in data

    def test_health_status_healthy(self, client: TestClient) -> None:
        """Health status is 'healthy'."""
        response = client.get("/health")
        assert response.json()["status"] == "healthy"

    def test_health_service_name(self, client: TestClient) -> None:
        """Health response contains correct service name."""
        response = client.get("/health")
        assert response.json()["service"] == "{spec.project_name}"

    def test_health_version_format(self, client: TestClient) -> None:
        """Version follows semver format."""
        response = client.get("/health")
        version = response.json()["version"]
        parts = version.split(".")
        assert len(parts) == 3
        assert all(p.isdigit() for p in parts)
'''

    def _test_api(self, spec: IntentSpec) -> str:
        return f'''"""API endpoint tests.

Project: {spec.project_name}
"""

from __future__ import annotations

from fastapi.testclient import TestClient


class TestRootEndpoint:
    """Tests for / root endpoint."""

    def test_root_returns_200(self, client: TestClient) -> None:
        """Root endpoint returns 200 OK."""
        response = client.get("/")
        assert response.status_code == 200

    def test_root_response_structure(self, client: TestClient) -> None:
        """Root response returns HTML content."""
        response = client.get("/")
        assert "<!DOCTYPE html>" in response.text
        assert "{spec.project_name}" in response.text

    def test_root_status_running(self, client: TestClient) -> None:
        """Root HTML includes running status indicator."""
        response = client.get("/")
        assert "Status: Running" in response.text

    def test_root_has_docs_link(self, client: TestClient) -> None:
        """Root HTML includes docs URL."""
        response = client.get("/")
        assert 'href="/docs"' in response.text


class TestDocsEndpoint:
    """Tests for /docs OpenAPI endpoint."""

    def test_docs_returns_200(self, client: TestClient) -> None:
        """Docs endpoint is accessible."""
        response = client.get("/docs")
        assert response.status_code == 200

    def test_redoc_disabled(self, client: TestClient) -> None:
        """ReDoc is disabled as configured."""
        response = client.get("/redoc")
        assert response.status_code == 404


class TestNotFound:
    """Tests for undefined routes."""

    def test_undefined_route_returns_404(self, client: TestClient) -> None:
        """Undefined routes return 404."""
        response = client.get("/nonexistent")
        assert response.status_code == 404
'''

    def _test_security(self, spec: IntentSpec) -> str:
        return f'''"""Security tests for the application.

Project: {spec.project_name}
Tests cover: input validation, auth patterns, response headers.
"""

from __future__ import annotations

from unittest.mock import patch

from fastapi.testclient import TestClient


class TestKeyvaultSecurity:
    """Key Vault integration security tests."""

    def test_keyvault_uses_managed_identity(self, client: TestClient) -> None:
        """Key Vault client uses DefaultAzureCredential (Managed Identity)."""
        with patch("src.app.main.DefaultAzureCredential") as mock_cred:
            with patch("src.app.main.SecretClient") as mock_kv:
                mock_kv.return_value.list_properties_of_secrets.return_value = []
                response = client.get("/keyvault/status")
                # Verify credential was instantiated
                mock_cred.assert_called()

    def test_keyvault_failure_returns_503(self, client: TestClient) -> None:
        """Key Vault failures return 503 Service Unavailable."""
        with patch("src.app.main.get_keyvault_client", side_effect=Exception("Connection failed")):
            response = client.get("/keyvault/status")
            assert response.status_code == 503
            assert "error" in response.json()["status"]

    def test_keyvault_missing_vault_name(self, client: TestClient, monkeypatch: object) -> None:
        """Missing KEY_VAULT_NAME raises ValueError."""
        import pytest

        from src.app.main import get_keyvault_client

        # Temporarily unset the env var
        import os
        with patch.dict(os.environ, {{"KEY_VAULT_NAME": ""}}):
            with pytest.raises(ValueError, match="KEY_VAULT_NAME"):
                get_keyvault_client()


class TestResponseHeaders:
    """Response header security tests."""

    def test_json_content_type(self, client: TestClient) -> None:
        """API responses use application/json content type."""
        response = client.get("/health")
        assert "application/json" in response.headers.get("content-type", "")


class TestInputValidation:
    """Input validation and injection prevention tests."""

    def test_unknown_query_params_ignored(self, client: TestClient) -> None:
        """Unknown query parameters are safely ignored."""
        response = client.get("/health?inject=<script>alert(1)</script>")
        assert response.status_code == 200

    def test_path_traversal_rejected(self, client: TestClient) -> None:
        """Path traversal attempts return 404 not 500."""
        response = client.get("/../../../etc/passwd")
        assert response.status_code in (404, 307)
'''

    def _test_config(self, spec: IntentSpec) -> str:
        return f'''"""Configuration tests.

Project: {spec.project_name}
Verifies environment-based configuration works correctly.
"""

from __future__ import annotations

import os
from unittest.mock import patch


class TestEnvironmentConfig:
    """Tests for environment variable configuration."""

    def test_app_name_configured(self) -> None:
        """APP_NAME constant is set correctly."""
        from src.app.main import APP_NAME

        assert APP_NAME == "{spec.project_name}"

    def test_version_configured(self) -> None:
        """VERSION constant follows semver."""
        from src.app.main import VERSION

        parts = VERSION.split(".")
        assert len(parts) == 3

    def test_default_port(self) -> None:
        """Default port is 8000."""
        with patch.dict(os.environ, {{"PORT": "8000"}}):
            port = int(os.getenv("PORT", "8000"))
            assert port == 8000

    def test_custom_port(self) -> None:
        """Custom PORT environment variable is respected."""
        with patch.dict(os.environ, {{"PORT": "3000"}}):
            port = int(os.getenv("PORT", "8000"))
            assert port == 3000
'''

    def _test_storage(self, spec: IntentSpec) -> str:
        return f'''"""Storage integration tests.

Project: {spec.project_name}
Tests for Azure Blob Storage connectivity.
"""

from __future__ import annotations

import os
from unittest.mock import MagicMock, patch

from fastapi.testclient import TestClient


class TestStorageEndpoint:
    """Tests for /storage/status endpoint."""

    def test_storage_status_connected(self, client: TestClient) -> None:
        """Storage status returns connected when accessible."""
        with patch("src.app.main.get_blob_client") as mock_client:
            mock_client.return_value.list_containers.return_value = []
            response = client.get("/storage/status")
            assert response.status_code == 200
            assert response.json()["status"] == "connected"

    def test_storage_failure_returns_503(self, client: TestClient) -> None:
        """Storage failures return 503."""
        with patch("src.app.main.get_blob_client", side_effect=Exception("Storage unavailable")):
            response = client.get("/storage/status")
            assert response.status_code == 503

    def test_storage_missing_url(self) -> None:
        """Missing STORAGE_ACCOUNT_URL raises ValueError."""
        import pytest

        from src.app.main import get_blob_client

        with patch.dict(os.environ, {{"STORAGE_ACCOUNT_URL": ""}}):
            with pytest.raises(ValueError, match="STORAGE_ACCOUNT_URL"):
                get_blob_client()
'''

    def _test_entity_crud(self, spec: IntentSpec) -> str:
        """Generate deterministic CRUD tests from the RouteManifest."""
        manifest = RouteBuilder.build(spec)
        lines = [
            f'"""Entity CRUD tests -- auto-generated from route manifest.',
            f'',
            f'Project: {spec.project_name}',
            f'Covers {manifest.route_count} routes across {len(manifest.entity_names)} entities.',
            f'"""',
            '',
            'from __future__ import annotations',
            '',
            'from fastapi.testclient import TestClient',
            '',
        ]

        for entity_name in manifest.entity_names:
            routes = manifest.routes_for_entity(entity_name)
            lines.append(f'')
            lines.append(f'class Test{entity_name}CRUD:')
            lines.append(f'    """{entity_name} entity CRUD tests."""')
            lines.append(f'')

            for route in routes:
                test_name = f"test_{route.action_name}"
                if route.action == RouteAction.LIST:
                    status_param = ""
                    if route.has_status_filter:
                        status_param = "?status=active"
                    lines.append(f'    def {test_name}_returns_list(self, client: TestClient) -> None:')
                    lines.append(f'        """GET {route.path} returns a list."""')
                    lines.append(f'        response = client.get("{route.path}{status_param}")')
                    lines.append(f'        assert response.status_code == 200')
                    lines.append(f'        assert isinstance(response.json(), list)')
                    lines.append(f'')

                elif route.action == RouteAction.CREATE:
                    # Build minimal create payload from entity fields
                    entity = next((e for e in spec.entities if e.name == entity_name), None)
                    payload_fields = {}
                    if entity:
                        for f in entity.fields:
                            if f.name in ("status", "state"):
                                continue
                            if f.type in ("str", "string"):
                                payload_fields[f.name] = f"test-{f.name}"
                            elif f.type in ("int", "integer"):
                                payload_fields[f.name] = 1
                            elif f.type in ("float",):
                                payload_fields[f.name] = 1.0
                            elif f.type in ("bool", "boolean"):
                                payload_fields[f.name] = True
                            else:
                                payload_fields[f.name] = f"test-{f.name}"
                    payload_str = repr(payload_fields)
                    lines.append(f'    def {test_name}_returns_201(self, client: TestClient) -> None:')
                    lines.append(f'        """POST {route.path} creates a new record."""')
                    lines.append(f'        response = client.post("{route.path}", json={payload_str})')
                    lines.append(f'        assert response.status_code == 201')
                    lines.append(f'        data = response.json()')
                    lines.append(f'        assert "id" in data')
                    lines.append(f'')

                elif route.action == RouteAction.GET:
                    # Use a known seed ID
                    sn = route.action_name.replace("get_", "")
                    lines.append(f'    def {test_name}_found(self, client: TestClient) -> None:')
                    lines.append(f'        """GET by ID returns the record."""')
                    lines.append(f'        response = client.get("{_route_path_with_id(route.path, sn)}")')
                    lines.append(f'        assert response.status_code in (200, 404)')
                    lines.append(f'')
                    lines.append(f'    def {test_name}_not_found(self, client: TestClient) -> None:')
                    lines.append(f'        """GET nonexistent ID returns 404."""')
                    lines.append(f'        response = client.get("{_route_path_404(route.path)}")')
                    lines.append(f'        assert response.status_code == 404')
                    lines.append(f'')

                elif route.action == RouteAction.DELETE:
                    lines.append(f'    def {test_name}_not_found(self, client: TestClient) -> None:')
                    lines.append(f'        """DELETE nonexistent returns 404."""')
                    lines.append(f'        response = client.delete("{_route_path_404(route.path)}")')
                    lines.append(f'        assert response.status_code == 404')
                    lines.append(f'')

                elif route.action == RouteAction.CUSTOM:
                    lines.append(f'    def {test_name}_returns_success(self, client: TestClient) -> None:')
                    lines.append(f'        """POST {route.path} action endpoint works."""')
                    sn = route.entity.lower()
                    lines.append(f'        response = client.post("{_route_path_with_id(route.path, sn)}")')
                    lines.append(f'        assert response.status_code in (200, 404)')
                    lines.append(f'')

        return "\n".join(lines)

    def _test_requirements(self) -> str:
        return """# Test dependencies
pytest>=7.4.0
pytest-cov>=4.1.0
pytest-asyncio>=0.23.0
httpx>=0.26.0
"""
