"""Enterprise DevEx Orchestrator -- Generated Application.

Project: ecommerce-returns-refund-management-pla
Description: Build an enterprise-grade ecommerce returns and refund management API that automates the full lifecycle of product returns, refund processing, and customer communication for a mid-to-large online reta
Generated by: Enterprise DevEx Orchestrator Agent

This is a production-grade FastAPI application with:
- Health check endpoint
- Managed Identity authentication
- Key Vault integration
- Structured logging
"""

from __future__ import annotations

import logging
import os
from datetime import datetime, timezone

from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient
from fastapi import FastAPI
from fastapi.responses import HTMLResponse, JSONResponse

from api.v1.router import router as v1_router

# -- Configuration ----------------------------------------------------
APP_NAME = "ecommerce-returns-refund-management-pla"
VERSION = "1.0.0"

# -- Logging ----------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format='{"timestamp":"%(asctime)s","level":"%(levelname)s","logger":"%(name)s","message":"%(message)s"}',
)
logger = logging.getLogger(APP_NAME)

# -- FastAPI Application ---------------------------------------------
app = FastAPI(
    title=APP_NAME,
    version=VERSION,
    description="Build an enterprise-grade ecommerce returns and refund management API that automates the full lifecycle of product returns, refund processing, and customer communication for a mid-to-large online reta",
    docs_url="/docs",
    redoc_url=None,
)

# -- Mount versioned API router --------------------------------------
app.include_router(v1_router, prefix="/api/v1", tags=["v1"])


# -- Key Vault Client ------------------------------------------------
def get_keyvault_client() -> SecretClient:
    """Create an authenticated Key Vault client using Managed Identity.
    
    Supports two configuration patterns:
    1. KEY_VAULT_URI - full vault URL (https://vault-name.vault.azure.net)
    2. KEY_VAULT_NAME - vault name only (will construct URL)
    """
    credential = DefaultAzureCredential(
        managed_identity_client_id=os.getenv("AZURE_CLIENT_ID")
    )
    
    # Try full URI first (recommended)
    vault_uri = os.getenv("KEY_VAULT_URI", "")
    if vault_uri:
        return SecretClient(vault_url=vault_uri, credential=credential)
    
    # Fallback to name-based construction
    vault_name = os.getenv("KEY_VAULT_NAME", "")
    if not vault_name:
        raise ValueError("Either KEY_VAULT_URI or KEY_VAULT_NAME must be set")
    
    return SecretClient(
        vault_url=f"https://{vault_name}.vault.azure.net",
        credential=credential
    )


# -- Health Endpoint --------------------------------------------------
@app.get("/health")
async def health():
    """Health check endpoint for liveness and readiness probes."""
    return {
        "status": "healthy",
        "service": APP_NAME,
        "version": VERSION,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }


# -- Root Endpoint (Enterprise Dashboard) ------
@app.get("/")
async def root():
    """Root endpoint -- enterprise dashboard."""
    html = f"""<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>{{APP_NAME}} \u2014 Operations Dashboard</title>
    <style>
        :root {{
            --primary: #0078d4;
            --primary-dark: #005a9e;
            --success: #107c10;
            --warning: #ff8c00;
            --danger: #d13438;
            --bg: #f3f2f1;
            --surface: #ffffff;
            --surface-alt: #faf9f8;
            --text: #323130;
            --text-secondary: #605e5c;
            --border: #edebe9;
            --shadow: 0 2px 8px rgba(0,0,0,.08);
            --shadow-lg: 0 8px 32px rgba(0,0,0,.12);
            --radius: 8px;
            --radius-lg: 12px;
        }}
        * {{ margin:0; padding:0; box-sizing:border-box; }}
        body {{ font-family:'Segoe UI',-apple-system,BlinkMacSystemFont,sans-serif; background:var(--bg); color:var(--text); min-height:100vh; }}
        .topbar {{ background:linear-gradient(135deg,#0078d4 0%,#005a9e 100%); color:white; padding:0 32px; height:48px; display:flex; align-items:center; justify-content:space-between; font-size:13px; box-shadow:0 1px 4px rgba(0,0,0,.15); position:sticky; top:0; z-index:100; }}
        .topbar-brand {{ display:flex; align-items:center; gap:10px; font-weight:600; font-size:14px; }}
        .topbar-brand svg {{ width:20px; height:20px; fill:white; }}
        .topbar-meta {{ display:flex; gap:16px; align-items:center; }}
        .topbar-meta span {{ opacity:.85; }}
        .env-badge {{ background:rgba(255,255,255,.2); padding:2px 10px; border-radius:12px; font-size:11px; text-transform:uppercase; font-weight:600; letter-spacing:.5px; }}
        .status-live {{ display:flex; align-items:center; gap:6px; font-size:12px; }}
        .status-live .dot {{ width:8px; height:8px; border-radius:50%; background:var(--success); animation:pulse 2s infinite; }}
        @keyframes pulse {{ 0%,100%{{opacity:1}} 50%{{opacity:.4}} }}
        .hero {{ background:linear-gradient(180deg,#005a9e 0%,#0078d4 50%,var(--bg) 100%); padding:40px 32px 56px; text-align:center; color:white; }}
        .hero h1 {{ font-size:26px; font-weight:600; margin-bottom:6px; }}
        .hero p {{ font-size:14px; opacity:.9; max-width:600px; margin:0 auto; line-height:1.5; }}
        .hero-pills {{ display:flex; gap:8px; justify-content:center; margin-top:12px; flex-wrap:wrap; }}
        .hero-pills span {{ background:rgba(255,255,255,.15); padding:3px 14px; border-radius:20px; font-size:11px; font-weight:500; }}
        .kpi-bar {{ max-width:1200px; margin:-32px auto 20px; padding:0 24px; display:grid; grid-template-columns:repeat(auto-fit,minmax(180px,1fr)); gap:16px; }}
        .kpi {{ background:var(--surface); border:1px solid var(--border); border-radius:var(--radius-lg); padding:20px; text-align:center; box-shadow:var(--shadow); transition:transform .15s; }}
        .kpi:hover {{ transform:translateY(-2px); box-shadow:var(--shadow-lg); }}
        .kpi .number {{ font-size:32px; font-weight:700; }}
        .kpi .label {{ font-size:11px; text-transform:uppercase; letter-spacing:.8px; color:var(--text-secondary); margin-top:4px; }}
        .kpi.ok .number {{ color:var(--success); }}
        .kpi.warn .number {{ color:var(--warning); }}
        .kpi.danger .number {{ color:var(--danger); }}
        .main {{ max-width:1200px; margin:0 auto 40px; padding:0 24px; }}
        .tab-bar {{ display:flex; gap:0; margin-bottom:0; border-bottom:2px solid var(--border); }}
        .tab {{ padding:12px 24px; font-size:13px; font-weight:600; cursor:pointer; border-bottom:2px solid transparent; margin-bottom:-2px; color:var(--text-secondary); transition:all .15s; }}
        .tab:hover {{ color:var(--text); }}
        .tab.active {{ color:var(--primary); border-bottom-color:var(--primary); }}
        .tab-panel {{ display:none; }}
        .tab-panel.active {{ display:block; }}
        .panel-toolbar {{ display:flex; justify-content:space-between; align-items:center; padding:16px 0; gap:12px; flex-wrap:wrap; }}
        .search-box {{ padding:8px 14px; border:1px solid var(--border); border-radius:var(--radius); font-size:13px; width:280px; outline:none; }}
        .search-box:focus {{ border-color:var(--primary); box-shadow:0 0 0 2px rgba(0,120,212,.15); }}
        .btn {{ padding:8px 18px; border:none; border-radius:var(--radius); font-size:13px; font-weight:600; cursor:pointer; transition:all .15s; display:inline-flex; align-items:center; gap:6px; }}
        .btn-primary {{ background:var(--primary); color:white; }}
        .btn-primary:hover {{ background:var(--primary-dark); }}
        .btn-success {{ background:var(--success); color:white; }}
        .btn-success:hover {{ opacity:.9; }}
        .btn-warning {{ background:var(--warning); color:white; }}
        .btn-warning:hover {{ opacity:.9; }}
        .btn-danger {{ background:var(--danger); color:white; }}
        .btn-danger:hover {{ opacity:.9; }}
        .btn-sm {{ padding:4px 10px; font-size:11px; }}
        .data-table {{ width:100%; border-collapse:separate; border-spacing:0; background:var(--surface); border:1px solid var(--border); border-radius:var(--radius-lg); overflow:hidden; box-shadow:var(--shadow); }}
        .data-table th {{ background:var(--surface-alt); padding:10px 14px; font-size:11px; text-transform:uppercase; letter-spacing:.5px; color:var(--text-secondary); text-align:left; font-weight:600; border-bottom:1px solid var(--border); }}
        .data-table td {{ padding:10px 14px; font-size:13px; border-bottom:1px solid var(--border); }}
        .data-table tr:last-child td {{ border-bottom:none; }}
        .data-table tr:hover td {{ background:#f0f6ff; }}
        .badge {{ display:inline-block; padding:2px 10px; border-radius:12px; font-size:11px; font-weight:600; text-transform:capitalize; }}
        .badge-pending {{ background:#fff3e0; color:#e65100; }}
        .badge-in_progress,.badge-in-progress,.badge-processing {{ background:#e3f2fd; color:#1565c0; }}
        .badge-approved,.badge-completed,.badge-processed {{ background:#e6f4ea; color:#1b5e20; }}
        .badge-rejected,.badge-cancelled,.badge-failed {{ background:#fce4ec; color:#b71c1c; }}
        .badge-escalated {{ background:#f3e5f5; color:#6a1b9a; }}
        .modal-overlay {{ display:none; position:fixed; top:0; left:0; width:100%; height:100%; background:rgba(0,0,0,.4); z-index:200; justify-content:center; align-items:center; }}
        .modal-overlay.open {{ display:flex; }}
        .modal {{ background:var(--surface); border-radius:var(--radius-lg); box-shadow:var(--shadow-lg); width:480px; max-width:90vw; max-height:80vh; overflow-y:auto; }}
        .modal-header {{ padding:16px 20px; border-bottom:1px solid var(--border); display:flex; justify-content:space-between; align-items:center; }}
        .modal-header h3 {{ font-size:16px; font-weight:600; }}
        .modal-close {{ background:none; border:none; font-size:20px; cursor:pointer; color:var(--text-secondary); }}
        .modal-body {{ padding:20px; }}
        .form-group {{ margin-bottom:14px; }}
        .form-group label {{ display:block; font-size:12px; font-weight:600; color:var(--text-secondary); margin-bottom:4px; text-transform:uppercase; letter-spacing:.3px; }}
        .form-group input,.form-group select,.form-group textarea {{ width:100%; padding:8px 12px; border:1px solid var(--border); border-radius:var(--radius); font-size:13px; outline:none; }}
        .form-group input:focus,.form-group select:focus,.form-group textarea:focus {{ border-color:var(--primary); box-shadow:0 0 0 2px rgba(0,120,212,.15); }}
        .modal-footer {{ padding:12px 20px; border-top:1px solid var(--border); display:flex; justify-content:flex-end; gap:8px; }}
        .toast {{ position:fixed; bottom:24px; right:24px; padding:12px 20px; border-radius:var(--radius); color:white; font-size:13px; font-weight:500; z-index:300; transform:translateY(80px); opacity:0; transition:all .3s; box-shadow:var(--shadow-lg); }}
        .toast.show {{ transform:translateY(0); opacity:1; }}
        .toast.success {{ background:var(--success); }}
        .toast.error {{ background:var(--danger); }}
        .detail-row {{ display:grid; grid-template-columns:140px 1fr; gap:8px; padding:6px 0; border-bottom:1px solid var(--border); font-size:13px; }}
        .detail-row:last-child {{ border-bottom:none; }}
        .detail-row .dl {{ font-weight:600; color:var(--text-secondary); }}
        .empty-state {{ text-align:center; padding:40px; color:var(--text-secondary); }}
        .empty-state .icon {{ font-size:48px; margin-bottom:12px; }}
        .footer {{ text-align:center; padding:24px; font-size:12px; color:var(--text-secondary); border-top:1px solid var(--border); max-width:1200px; margin:0 auto; }}
        .footer a {{ color:var(--primary); text-decoration:none; }}
        .sidebar-info {{ display:grid; grid-template-columns:1fr 1fr; gap:16px; margin-top:16px; }}
        .info-card {{ background:var(--surface); border:1px solid var(--border); border-radius:var(--radius-lg); padding:16px; box-shadow:var(--shadow); }}
        .info-card h4 {{ font-size:12px; text-transform:uppercase; letter-spacing:.5px; color:var(--text-secondary); margin-bottom:8px; }}
        .info-card ul {{ list-style:none; font-size:13px; }}
        .info-card ul li {{ padding:4px 0; display:flex; align-items:center; gap:8px; }}
        .info-card ul li::before {{ content:''; width:6px; height:6px; border-radius:50%; background:var(--primary); flex-shrink:0; }}
    </style>
</head>
<body>
    <nav class=\"topbar\">
        <div class=\"topbar-brand\">
            <svg viewBox=\"0 0 24 24\"><path d=\"M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5\"/></svg>
            {{APP_NAME}}
        </div>
        <div class=\"topbar-meta\">
            <div class=\"status-live\"><span class=\"dot\"></span>Live</div>
            <span class=\"env-badge\">dev</span>
            <span>eastus2</span>
        </div>
    </nav>
    <section class=\"hero\">
        <h1>{{APP_NAME}}</h1>
        <p>Build an enterprise-grade ecommerce returns and refund management API that automates the full lifecycle of product returns, refund processing, and customer communication for a mid-to-large online reta</p>
        <div class=\"hero-pills\">
            <span>v{{VERSION}}</span>
            <span>Container Apps</span>
            <span>eastus2</span>
        </div>
    </section>
    <div class=\"kpi-bar\">
        <div class=\"kpi\" id=\"kpi-refunds\"><div class=\"number\" id=\"count-refunds\">--</div><div class=\"label\">Total Refunds</div></div>
        <div class=\"kpi\" id=\"kpi-returns\"><div class=\"number\" id=\"count-returns\">--</div><div class=\"label\">Total Returns</div></div>
        <div class=\"kpi\" id=\"kpi-policies\"><div class=\"number\" id=\"count-policies\">--</div><div class=\"label\">Total Policies</div></div>
        <div class=\"kpi\" id=\"kpi-eligibilities\"><div class=\"number\" id=\"count-eligibilities\">--</div><div class=\"label\">Total Eligibilities</div></div>
        <div class=\"kpi\" id=\"kpi-orders\"><div class=\"number\" id=\"count-orders\">--</div><div class=\"label\">Total Orders</div></div>
        <div class=\"kpi warn\" id=\"kpi-pending\"><div class=\"number\" id=\"count-pending\">--</div><div class=\"label\">Pending Review</div></div>
        <div class=\"kpi ok\" id=\"kpi-completed\"><div class=\"number\" id=\"count-completed\">--</div><div class=\"label\">Completed</div></div>
    </div>
    <div class=\"main\">
        <div class=\"tab-bar\">
            <div class=\"tab active\" data-tab=\"refunds\">Refunds</div>
            <div class=\"tab\" data-tab=\"returns\">Returns</div>
            <div class=\"tab\" data-tab=\"policies\">Policies</div>
            <div class=\"tab\" data-tab=\"eligibilities\">Eligibilities</div>
            <div class=\"tab\" data-tab=\"orders\">Orders</div>
            <div class=\"tab\" data-tab=\"system\">System</div>
        </div>
        <div class=\"tab-panel active\" id=\"panel-refunds\"><div class=\"panel-toolbar\"><input type=\"text\" class=\"search-box\" placeholder=\"Search refunds...\" oninput=\"filterTable(&#39;refunds&#39;, this.value)\"><button class=\"btn btn-primary\" onclick=\"openCreateModal(&#39;Refund&#39;, &#39;refunds&#39;)\">+ New Refund</button></div><table class=\"data-table\" id=\"table-refunds\"><thead><tr><th>ID</th><th>Amount</th><th>Currency</th><th>Method</th><th>Customer Id</th><th>User Id</th><th>Order Id</th><th>Product Id</th><th>Status</th><th>Actions</th></tr></thead><tbody id=\"tbody-refunds\"><tr><td colspan=\"10\" style=\"text-align:center;padding:24px;color:var(--text-secondary)\">Loading...</td></tr></tbody></table></div>
        <div class=\"tab-panel\" id=\"panel-returns\"><div class=\"panel-toolbar\"><input type=\"text\" class=\"search-box\" placeholder=\"Search returns...\" oninput=\"filterTable(&#39;returns&#39;, this.value)\"><button class=\"btn btn-primary\" onclick=\"openCreateModal(&#39;Return&#39;, &#39;returns&#39;)\">+ New Return</button></div><table class=\"data-table\" id=\"table-returns\"><thead><tr><th>ID</th><th>Reason</th><th>Priority</th><th>Customer Id</th><th>User Id</th><th>Order Id</th><th>Product Id</th><th>Status</th><th>Actions</th></tr></thead><tbody id=\"tbody-returns\"><tr><td colspan=\"9\" style=\"text-align:center;padding:24px;color:var(--text-secondary)\">Loading...</td></tr></tbody></table></div>
        <div class=\"tab-panel\" id=\"panel-policies\"><div class=\"panel-toolbar\"><input type=\"text\" class=\"search-box\" placeholder=\"Search policies...\" oninput=\"filterTable(&#39;policies&#39;, this.value)\"><button class=\"btn btn-primary\" onclick=\"openCreateModal(&#39;Policy&#39;, &#39;policies&#39;)\">+ New Policy</button></div><table class=\"data-table\" id=\"table-policies\"><thead><tr><th>ID</th><th>Customer Id</th><th>User Id</th><th>Order Id</th><th>Product Id</th><th>Status</th><th>Actions</th></tr></thead><tbody id=\"tbody-policies\"><tr><td colspan=\"7\" style=\"text-align:center;padding:24px;color:var(--text-secondary)\">Loading...</td></tr></tbody></table></div>
        <div class=\"tab-panel\" id=\"panel-eligibilities\"><div class=\"panel-toolbar\"><input type=\"text\" class=\"search-box\" placeholder=\"Search eligibilities...\" oninput=\"filterTable(&#39;eligibilities&#39;, this.value)\"><button class=\"btn btn-primary\" onclick=\"openCreateModal(&#39;Eligibility&#39;, &#39;eligibilities&#39;)\">+ New Eligibility</button></div><table class=\"data-table\" id=\"table-eligibilities\"><thead><tr><th>ID</th><th>Customer Id</th><th>User Id</th><th>Order Id</th><th>Product Id</th><th>Status</th><th>Actions</th></tr></thead><tbody id=\"tbody-eligibilities\"><tr><td colspan=\"7\" style=\"text-align:center;padding:24px;color:var(--text-secondary)\">Loading...</td></tr></tbody></table></div>
        <div class=\"tab-panel\" id=\"panel-orders\"><div class=\"panel-toolbar\"><input type=\"text\" class=\"search-box\" placeholder=\"Search orders...\" oninput=\"filterTable(&#39;orders&#39;, this.value)\"><button class=\"btn btn-primary\" onclick=\"openCreateModal(&#39;Order&#39;, &#39;orders&#39;)\">+ New Order</button></div><table class=\"data-table\" id=\"table-orders\"><thead><tr><th>ID</th><th>Reason</th><th>Priority</th><th>Customer Id</th><th>User Id</th><th>Product Id</th><th>Status</th><th>Actions</th></tr></thead><tbody id=\"tbody-orders\"><tr><td colspan=\"8\" style=\"text-align:center;padding:24px;color:var(--text-secondary)\">Loading...</td></tr></tbody></table></div>
        <div class=\"tab-panel\" id=\"panel-system\"><div class=\"sidebar-info\"><div class=\"info-card\"><h4>Architecture</h4><ul><li>Compute: Container Apps</li><li>Data: Cosmos Db + Redis</li><li>Security: Managed Identity</li><li>Monitoring: Log Analytics</li></ul></div><div class=\"info-card\"><h4>API Documentation</h4><ul><li><a href=\"/docs\" style=\"color:var(--primary)\">Interactive API Docs</a></li><li><a href=\"/health\" style=\"color:var(--primary)\">Health Check</a></li><li><a href=\"/keyvault/status\" style=\"color:var(--primary)\">Key Vault Status</a></li></ul></div></div></div>
    </div>
    <div class=\"modal-overlay\" id=\"createModal\">
        <div class=\"modal\">
            <div class=\"modal-header\"><h3 id=\"modalTitle\">Create</h3><button class=\"modal-close\" onclick=\"closeModal()\">&times;</button></div>
            <div class=\"modal-body\" id=\"modalBody\"></div>
            <div class=\"modal-footer\"><button class=\"btn\" onclick=\"closeModal()\">Cancel</button><button class=\"btn btn-primary\" id=\"modalSubmit\" onclick=\"submitCreate()\">Create</button></div>
        </div>
    </div>
    <div class=\"modal-overlay\" id=\"detailModal\">
        <div class=\"modal\">
            <div class=\"modal-header\"><h3 id=\"detailTitle\">Details</h3><button class=\"modal-close\" onclick=\"closeDetail()\">&times;</button></div>
            <div class=\"modal-body\" id=\"detailBody\"></div>
            <div class=\"modal-footer\" id=\"detailActions\"></div>
        </div>
    </div>
    <div id=\"toast\" class=\"toast\"></div>
    <footer class=\"footer\">{{APP_NAME}} v{{VERSION}} \u00b7 <a href=\"/docs\">API Docs</a> \u00b7 Enterprise DevEx Orchestrator</footer>
    <script>
        
        const ENTITIES = [
        {{
                "name": "Refund",
                "slug": "refunds",
                "id_field": "refund_id",
                "table_fields": [
                        "amount",
                        "currency",
                        "method",
                        "customer_id",
                        "user_id",
                        "order_id",
                        "product_id",
                        "status"
                ],
                "form_fields": [
                        {{
                                "name": "amount",
                                "type": "float"
                        }},
                        {{
                                "name": "currency",
                                "type": "str"
                        }},
                        {{
                                "name": "method",
                                "type": "str"
                        }},
                        {{
                                "name": "customer_id",
                                "type": "str"
                        }},
                        {{
                                "name": "user_id",
                                "type": "str"
                        }},
                        {{
                                "name": "order_id",
                                "type": "str"
                        }},
                        {{
                                "name": "product_id",
                                "type": "str"
                        }},
                        {{
                                "name": "notes",
                                "type": "str"
                        }}
                ],
                "actions": [
                        "approve",
                        "reject",
                        "process",
                        "complete",
                        "escalate",
                        "inspect"
                ]
        }},
        {{
                "name": "Return",
                "slug": "returns",
                "id_field": "return_id",
                "table_fields": [
                        "reason",
                        "priority",
                        "customer_id",
                        "user_id",
                        "order_id",
                        "product_id",
                        "status"
                ],
                "form_fields": [
                        {{
                                "name": "reason",
                                "type": "str"
                        }},
                        {{
                                "name": "priority",
                                "type": "str"
                        }},
                        {{
                                "name": "customer_id",
                                "type": "str"
                        }},
                        {{
                                "name": "user_id",
                                "type": "str"
                        }},
                        {{
                                "name": "order_id",
                                "type": "str"
                        }},
                        {{
                                "name": "product_id",
                                "type": "str"
                        }},
                        {{
                                "name": "items",
                                "type": "list[str]"
                        }},
                        {{
                                "name": "notes",
                                "type": "str"
                        }}
                ],
                "actions": [
                        "approve",
                        "reject",
                        "process",
                        "complete",
                        "escalate",
                        "inspect"
                ]
        }},
        {{
                "name": "Policy",
                "slug": "policies",
                "id_field": "policy_id",
                "table_fields": [
                        "customer_id",
                        "user_id",
                        "order_id",
                        "product_id",
                        "status"
                ],
                "form_fields": [
                        {{
                                "name": "customer_id",
                                "type": "str"
                        }},
                        {{
                                "name": "user_id",
                                "type": "str"
                        }},
                        {{
                                "name": "order_id",
                                "type": "str"
                        }},
                        {{
                                "name": "product_id",
                                "type": "str"
                        }},
                        {{
                                "name": "notes",
                                "type": "str"
                        }}
                ],
                "actions": []
        }},
        {{
                "name": "Eligibility",
                "slug": "eligibilities",
                "id_field": "eligibility_id",
                "table_fields": [
                        "customer_id",
                        "user_id",
                        "order_id",
                        "product_id",
                        "status"
                ],
                "form_fields": [
                        {{
                                "name": "customer_id",
                                "type": "str"
                        }},
                        {{
                                "name": "user_id",
                                "type": "str"
                        }},
                        {{
                                "name": "order_id",
                                "type": "str"
                        }},
                        {{
                                "name": "product_id",
                                "type": "str"
                        }},
                        {{
                                "name": "notes",
                                "type": "str"
                        }}
                ],
                "actions": []
        }},
        {{
                "name": "Order",
                "slug": "orders",
                "id_field": "order_id",
                "table_fields": [
                        "reason",
                        "priority",
                        "customer_id",
                        "user_id",
                        "product_id",
                        "status"
                ],
                "form_fields": [
                        {{
                                "name": "reason",
                                "type": "str"
                        }},
                        {{
                                "name": "priority",
                                "type": "str"
                        }},
                        {{
                                "name": "customer_id",
                                "type": "str"
                        }},
                        {{
                                "name": "user_id",
                                "type": "str"
                        }},
                        {{
                                "name": "product_id",
                                "type": "str"
                        }},
                        {{
                                "name": "items",
                                "type": "list[str]"
                        }},
                        {{
                                "name": "notes",
                                "type": "str"
                        }}
                ],
                "actions": [
                        "approve",
                        "reject",
                        "process",
                        "complete",
                        "escalate",
                        "inspect"
                ]
        }}
];
        let allData = {{}};

        async function loadAll() {{
            let totalPending = 0, totalCompleted = 0;
            for (const ent of ENTITIES) {{
                try {{
                    const r = await fetch('/api/v1/' + ent.slug);
                    const d = await r.json();
                    const rows = Array.isArray(d) ? d : (d.value || d.items || d.data || []);
                    allData[ent.slug] = rows;
                    document.getElementById('count-' + ent.slug).textContent = rows.length;
                    totalPending += rows.filter(r => r.status === 'pending').length;
                    totalCompleted += rows.filter(r => ['completed','approved','processed'].includes(r.status)).length;
                    renderTable(ent, rows);
                }} catch(e) {{
                    console.error('Failed to load ' + ent.slug, e);
                    document.getElementById('count-' + ent.slug).textContent = '!';
                }}
            }}
            document.getElementById('count-pending').textContent = totalPending;
            document.getElementById('count-completed').textContent = totalCompleted;
        }}

        function renderTable(ent, rows) {{
            const tbody = document.getElementById('tbody-' + ent.slug);
            if (!rows.length) {{
                tbody.innerHTML = '<tr><td colspan="' + (ent.table_fields.length + 2) + '" style="text-align:center;padding:32px;color:var(--text-secondary)"><div class="empty-state"><div class="icon">📭</div><div>No ' + ent.slug.replace(/_/g,' ') + ' yet</div></div></td></tr>';
                return;
            }}
            tbody.innerHTML = rows.map(row => {{
                const idShort = (row.id || '').substring(0, 8);
                let cells = '<td style="font-family:Consolas,monospace;font-size:12px;cursor:pointer;color:var(--primary)" onclick="openDetail(\'' + ent.slug + '\',\'' + row.id + '\')">' + idShort + '...</td>';
                ent.table_fields.forEach(f => {{
                    const val = row[f] != null ? row[f] : '-';
                    if (f === 'status') {{
                        cells += '<td><span class="badge badge-' + String(val).replace(/ /g,'-') + '">' + val + '</span></td>';
                    }} else if (f === 'amount') {{
                        cells += '<td style="font-weight:600">$' + Number(val).toFixed(2) + '</td>';
                    }} else if (f === 'priority') {{
                        const pcolor = val === 'high' ? 'var(--danger)' : val === 'medium' ? 'var(--warning)' : 'var(--text-secondary)';
                        cells += '<td style="font-weight:600;color:' + pcolor + '">' + val + '</td>';
                    }} else if (f === 'created_at') {{
                        cells += '<td>' + new Date(val).toLocaleDateString() + '</td>';
                    }} else {{
                        cells += '<td>' + val + '</td>';
                    }}
                }});
                let actionBtns = '';
                if (row.status === 'pending') {{
                    if (ent.actions.includes('approve')) actionBtns += '<button class="btn btn-success btn-sm" onclick="doAction(\'' + ent.slug + '\',\'' + row.id + '\',\'approve\')">Approve</button> ';
                    if (ent.actions.includes('reject')) actionBtns += '<button class="btn btn-danger btn-sm" onclick="doAction(\'' + ent.slug + '\',\'' + row.id + '\',\'reject\')">Reject</button> ';
                }}
                if (row.status === 'approved' && ent.actions.includes('process')) {{
                    actionBtns += '<button class="btn btn-warning btn-sm" onclick="doAction(\'' + ent.slug + '\',\'' + row.id + '\',\'process\')">Process</button> ';
                }}
                if (['pending','approved','in_progress'].includes(row.status) && ent.actions.includes('escalate')) {{
                    actionBtns += '<button class="btn btn-sm" style="background:#7b1fa2;color:white" onclick="doAction(\'' + ent.slug + '\',\'' + row.id + '\',\'escalate\')">Escalate</button> ';
                }}
                if (!actionBtns) actionBtns = '<span style="color:var(--text-secondary);font-size:12px">No actions</span>';
                cells += '<td>' + actionBtns + '</td>';
                return '<tr>' + cells + '</tr>';
            }}).join('');
        }}

        function filterTable(slug, query) {{
            const rows = allData[slug] || [];
            const q = query.toLowerCase();
            const ent = ENTITIES.find(e => e.slug === slug);
            const filtered = rows.filter(r => JSON.stringify(r).toLowerCase().includes(q));
            renderTable(ent, filtered);
        }}

        // Tabs
        document.querySelectorAll('.tab').forEach(tab => {{
            tab.addEventListener('click', () => {{
                document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
                document.querySelectorAll('.tab-panel').forEach(p => p.classList.remove('active'));
                tab.classList.add('active');
                document.getElementById('panel-' + tab.dataset.tab).classList.add('active');
            }});
        }});

        // Create modal
        let createTarget = {{}};
        function openCreateModal(entityName, slug) {{
            const ent = ENTITIES.find(e => e.slug === slug);
            createTarget = {{ entityName, slug }};
            document.getElementById('modalTitle').textContent = 'Create New ' + entityName;
            let formHtml = '';
            ent.form_fields.forEach(f => {{
                const label = f.name.replace(/_/g, ' ');
                if (f.type === 'list' || f.type === 'list[str]') {{
                    formHtml += '<div class="form-group"><label>' + label + '</label><input type="text" name="' + f.name + '" placeholder="Comma-separated values"></div>';
                }} else if (f.type === 'float' || f.type === 'int') {{
                    formHtml += '<div class="form-group"><label>' + label + '</label><input type="number" name="' + f.name + '" step="any"></div>';
                }} else if (f.type === 'bool') {{
                    formHtml += '<div class="form-group"><label>' + label + '</label><select name="' + f.name + '"><option value="true">Yes</option><option value="false">No</option></select></div>';
                }} else {{
                    formHtml += '<div class="form-group"><label>' + label + '</label><input type="text" name="' + f.name + '"></div>';
                }}
            }});
            document.getElementById('modalBody').innerHTML = formHtml;
            document.getElementById('createModal').classList.add('open');
        }}
        function closeModal() {{ document.getElementById('createModal').classList.remove('open'); }}

        async function submitCreate() {{
            const ent = ENTITIES.find(e => e.slug === createTarget.slug);
            const body = {{}};
            ent.form_fields.forEach(f => {{
                const input = document.querySelector('#modalBody [name="' + f.name + '"]');
                if (!input) return;
                let val = input.value;
                if (f.type === 'list' || f.type === 'list[str]') {{
                    body[f.name] = val ? val.split(',').map(s => s.trim()) : [];
                }} else if (f.type === 'float') {{
                    body[f.name] = parseFloat(val) || 0;
                }} else if (f.type === 'int') {{
                    body[f.name] = parseInt(val) || 0;
                }} else if (f.type === 'bool') {{
                    body[f.name] = val === 'true';
                }} else {{
                    body[f.name] = val;
                }}
            }});
            try {{
                const r = await fetch('/api/v1/' + createTarget.slug, {{ method:'POST', headers:{{'Content-Type':'application/json'}}, body:JSON.stringify(body) }});
                if (r.ok) {{
                    showToast('success', createTarget.entityName + ' created successfully');
                    closeModal();
                    loadAll();
                }} else {{
                    const err = await r.json();
                    showToast('error', 'Error: ' + (err.detail || JSON.stringify(err)));
                }}
            }} catch(e) {{
                showToast('error', 'Network error');
            }}
        }}

        // Detail modal
        function openDetail(slug, id) {{
            const ent = ENTITIES.find(e => e.slug === slug);
            const rows = allData[slug] || [];
            const row = rows.find(r => r.id === id);
            if (!row) return;
            document.getElementById('detailTitle').textContent = ent.name + ' Details';
            let html = '';
            Object.entries(row).forEach(([k,v]) => {{
                const label = k.replace(/_/g,' ').replace(/\\b\\w/g, c => c.toUpperCase());
                let display = v;
                if (Array.isArray(v)) display = v.join(', ');
                if (k === 'status') display = '<span class="badge badge-' + String(v).replace(/ /g,'-') + '">' + v + '</span>';
                if (k === 'amount') display = '$' + Number(v).toFixed(2);
                html += '<div class="detail-row"><div class="dl">' + label + '</div><div>' + display + '</div></div>';
            }});
            document.getElementById('detailBody').innerHTML = html;

            // Action buttons in detail
            let actionsHtml = '<button class="btn" onclick="closeDetail()">Close</button>';
            if (row.status === 'pending') {{
                if (ent.actions.includes('approve')) actionsHtml += ' <button class="btn btn-success" onclick="doAction(\'' + slug + '\',\'' + id + '\',\'approve\');closeDetail()">Approve</button>';
                if (ent.actions.includes('reject')) actionsHtml += ' <button class="btn btn-danger" onclick="doAction(\'' + slug + '\',\'' + id + '\',\'reject\');closeDetail()">Reject</button>';
            }}
            if (row.status === 'approved' && ent.actions.includes('process')) {{
                actionsHtml += ' <button class="btn btn-warning" onclick="doAction(\'' + slug + '\',\'' + id + '\',\'process\');closeDetail()">Process</button>';
            }}
            document.getElementById('detailActions').innerHTML = actionsHtml;
            document.getElementById('detailModal').classList.add('open');
        }}
        function closeDetail() {{ document.getElementById('detailModal').classList.remove('open'); }}

        async function doAction(slug, id, action) {{
            if (!confirm('Are you sure you want to ' + action + ' this record?')) return;
            try {{
                const r = await fetch('/api/v1/' + slug + '/' + id + '/' + action, {{ method:'POST' }});
                if (r.ok) {{
                    showToast('success', action.charAt(0).toUpperCase() + action.slice(1) + ' completed');
                    loadAll();
                }} else {{
                    const err = await r.json();
                    showToast('error', 'Error: ' + (err.detail || 'Action failed'));
                }}
            }} catch(e) {{
                showToast('error', 'Network error');
            }}
        }}

        function showToast(type, msg) {{
            const t = document.getElementById('toast');
            t.textContent = msg;
            t.className = 'toast ' + type + ' show';
            setTimeout(() => {{ t.classList.remove('show'); }}, 3000);
        }}

        // Init
        loadAll();
        setInterval(loadAll, 30000);

    </script>
</body>
</html>
"""
    return HTMLResponse(content=html)


# -- Key Vault Status ------------------------------------------------
@app.get("/keyvault/status")
async def keyvault_status():
    """Check Key Vault connectivity via Managed Identity."""
    try:
        client = get_keyvault_client()
        # List secrets to verify access (limited to 1)
        secrets = list(client.list_properties_of_secrets(max_page_size=1))
        return {
            "status": "connected",
            "vault_accessible": True,
        }
    except Exception as e:
        logger.error(f"Key Vault health check failed: {e}")
        return JSONResponse(
            status_code=503,
            content={"status": "error", "detail": str(e)},
        )


# -- Startup Event ----------------------------------------------------
@app.on_event("startup")
async def startup():
    """Application startup tasks."""
    logger.info(f"{APP_NAME} v{VERSION} starting up")
    logger.info(f"Environment: {os.getenv('ENVIRONMENT', 'unknown')}")


@app.on_event("shutdown")
async def shutdown():
    """Application shutdown tasks."""
    logger.info(f"{APP_NAME} shutting down")


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", "8000"))
    uvicorn.run(app, host="0.0.0.0", port=port)
